"""Second half of findings.json: strike detection, news latency, S2/S1, market lead, data access, outage QA, night lights. Merges with findings_core.json."""
import json, pandas as pd, glob
B='/Users/tomalmog/projects/kingdom/explore/wardamage/'
core=json.load(open(B+'findings_core.json')); sb=json.load(open(B+'score_out/scoreboard_summary.json')); ob=json.load(open(B+'data/outage_robustness.json')); s2=pd.read_csv(B+'s2s1_out/s2s1_results.csv')
R=lambda m,v,n=None,note='': {'metric':m,'value':v,'n':n,'note':note}
DS={'gibs':{'name':'NASA GIBS WMTS vector tiles: VIIRS 375 m thermal anomalies','url':'https://gibs.earthdata.nasa.gov/wmts/epsg4326/best/','access':'keyless'},'gdelt':{'name':'GDELT 2.0 raw 15-minute export files','url':'http://data.gdeltproject.org/gdeltv2/','access':'keyless (DOC API returned HTTP 429)'},
 'wiki':{'name':'Wikipedia 2026 Iran war pages + HRW reports (event list)','url':'https://en.wikipedia.org/wiki/2026_Iran_war','access':'keyless'},'s2':{'name':'Sentinel-2 L2A COGs (Element84 Earth Search)','url':'https://earth-search.aws.element84.com/v1','access':'keyless'},'s1':{'name':'Sentinel-1 RTC (Microsoft Planetary Computer)','url':'https://planetarycomputer.microsoft.com/api/stac/v1','access':'anonymous SAS token'},
 'firms':{'name':'NASA FIRMS archive / 7-day files','url':'https://firms.modaps.eosdis.nasa.gov/data/country/','access':'keyless to 2024; 2025+ 404; API needs MAP_KEY'},'px':{'name':'yfinance/FRED prices cached in WarSignal repo','url':'local: voloridge_hackmit/data/raw/finance/prices.parquet','access':'read-only local'},
 'dnb':{'name':'NASA GIBS WMS VIIRS DNB at-sensor radiance','url':'https://gibs.earthdata.nasa.gov/wms/epsg4326/best/wms.cgi?LAYERS=VIIRS_NOAA20_DayNightBand_At_Sensor_Radiance','access':'keyless; saturates at 38.2 nW'}}
F=[]
o,sc,pl=sb['overall'],sb['by_site_class'],sb['placebo_event_sites']
F.append({'id':'viirs_strike_scoreboard','title':'Reported vs observed: 72 dated physical events scored against VIIRS active fire','one_liner':'VIIRS 375 m active fire sees 21% of reported strikes (28% at non-flare sites, 13% at permanent-flare sites); the detector almost never false-alarms, so the misses are real non-detections, and cloud does not explain them.',
 'datasets':[DS['gibs'],DS['wiki'],DS['gdelt']],'mechanism':'A strike that ignites hydrocarbons produces a multi-MW thermal anomaly visible at the next overpass if it is still burning, unobscured and outside an existing flare footprint.','method':'Event list (66 war events + 6 from June 2025) compiled from Wikipedia/HRW by sub-agents with no access to hotspot data; coordinates from OSM / pre-June-2025 flare clusters / approximate. Detector: novel 0.005 deg cells or FRP excess in the 72 h after the event; verdicts reviewed, auto-verdict retained. Placebo: same rule on 2,223 pre-war site-windows.',
 'results':[R('hits / ambiguous / miss',f"{o['hit']} / {o['ambiguous']} / {o['miss']}",o['n'],f"hit rate {o['hit_rate']}"),R('hit rate non-flare sites',sc['non_flare']['hit_rate'],sc['non_flare']['n']),R('hit rate permanent-flare sites',sc['permanent_flare']['hit_rate'],sc['permanent_flare']['n']),
  R('by asset type hits/n','tank farm 4/8, depot 4/10, terminal 2/5, refinery 3/12, port 2/7; gas processing 0/4, LNG 0/2, petrochemical 0/6, steel 0/2, smelter 0/2, tankers 0/5, airbases/airports 0/5',72),R('placebo false-positive rate per 72 h site-window',pl['window_fpr'],pl['n_windows'],f"flare sites {pl['window_fpr_flare_sites']}, non-flare {pl['window_fpr_nonflare_sites']}"),
  R('events with neighbouring reference flares visible in first 24 h that were still misses','20 of 23',23,'cloud is not the main reason for misses'),R('largest hits (peak daily FRP MW)','Lavan 1768, Salalah fuel tanks 1412 (7 days), Shahr-e Rey 763, Sirri 554',None),R('satellite-first candidates matched to news afterwards','2 matched, 1 partial, 8 unmatched',11,'excluded from hit rates')],
 'controls':'Event list built blind to satellite data; placebo windows; auto vs reviewed verdict both stored; satellite-first discoveries kept separate.','verdict':'partial','known_or_novel':'known method (Economist war-fire model, Bellingcat FIRMS use); the scored hit/miss table for this war is new','prior_art':['https://github.com/TheEconomist/the-economist-war-fire-model','https://smallwarsjournal.com/2026/03/25/fire-detection-as-a-proxy-for-combat-the-economist/'],
 'figures':[B+'score_out/fig_timeline_strip.png',B+'score_out/fig_hitmiss_latency.png',B+'asset_events.png'],'scripts':sorted(glob.glob(B+'score_*.py'))+[B+'novel.py'],'caveats':'Event dates mostly from Wikipedia with few clock times (4 of 72); approximate coordinates +-2-3 km; 7 manual verdict overrides (documented per row); two 2025 rows added from sub-agent memory, one without a citation.'})
l=sb['latency_vs_news_h']
F.append({'id':'satellite_before_news','title':'Does orbit see a strike before the news does?','one_liner':'No usable lead: the first overpass is a median 2.2 h before the first English GDELT article naming the site, but once ~3 h product latency is added it is 0.8 h after, and the GDELT time is itself an upper bound on when news broke.',
 'datasets':[DS['gibs'],DS['gdelt']],'mechanism':'VIIRS gives ~2 looks per day per location (three satellites within ~50 min of each other) plus ~3 h NRT latency; news and social media are minutes.','method':'For the 11 hits with a GDELT timestamp: first detection overpass time minus first 15-minute GDELT export URL naming the site. Abqaiq 2019 as a historical check.',
 'results':[R('median (IQR) overpass minus first news, hours',f"{l['median']} ({round(l['p25'],1)}..{l['p75']})",l['n'],f"range {l['min']}..{l['max']}"),R('median with 3 h NRT latency added',l['with_3h_nrt_data_latency']['median'],l['n'],f"satellite first in {l['with_3h_nrt_data_latency']['n_satellite_before_news']} of 11"),R('only event with a reported strike clock time (Lavan): detection minus strike',4.0,1,'hours'),R('Abqaiq 14 Sep 2019: first overpass after attack','about 8 h (attack ~01:00 UTC, first overpass 09:24 UTC)',1,'news within ~1-2 h')],
 'controls':'Latency reported both as overpass time and as data-availability time.','verdict':'rejected','known_or_novel':'known','prior_art':[],'figures':[B+'score_out/fig_hitmiss_latency.png'],'scripts':[B+'score_news.py',B+'score_gdelt_fetch.py',B+'score_gdelt_index.py'],
 'caveats':'GDELT English URL slugs miss wires, liveblogs, Farsi/Arabic and social media, so true news times are earlier; one -19.5 h value is a date ambiguity; the 3 h latency is assumed, not measured.'})
def row(site,ev,meth): 
    x=s2[(s2.site==site)&s2.event.str.contains(ev)&s2.method.str.contains(meth)]; return x.iloc[0] if len(x) else None
F.append({'id':'s2_s1_strikes_at_flare_sites','title':'Can Sentinel-2 SWIR or Sentinel-1 backscatter recover the strikes VIIRS missed at flaring sites?','one_liner':'No. Both positive controls are recovered (Tehran Rey burn scar is the top blob site-wide; Fujairah tank damage is the top Sentinel-1 blob at +26 h with zero placebo blobs that size), but Ras Laffan and South Pars remain misses or ambiguous: the damage is sub-pixel at 20 m, the first clear optical scene came 11-31 days later, and novel heat cannot be separated from emergency flaring.',
 'datasets':[DS['s2'],DS['s1'],DS['gibs']],'mechanism':'20 m SWIR resolves heat inside process units and burn scars; C-band backscatter changes when metal structures collapse.','method':'Windowed COG reads, 2025-10 to 2026-04. (a) novel SWIR hot-pixel clusters vs a persistent-flare mask; (b) B12/B11/B8A before/after differencing with local-background removal, nulls from 87-197 placebo scene pairs per site; (c) Sentinel-1 VV log-ratio first looks per relative orbit with 27-42 null looks; (d) 4-vs-4 scene stacks. Blind whole-site blob ranking, then distance to reported location.',
 'results':[R('Tehran Rey: S2 burn-scar blob','175 px (7 ha), rank 1 of 21, 388 m from VIIRS point; 0.01 placebo blobs per pair at that size and peak',150,'first clear scene +9.5 d; active fire seen through cloud at +4.5 d (26 px vs null max 7)'),R('Fujairah 3 Mar: S1 first look','335 px (3.35 ha), +9 dB, rank 1 of 48, 78 m from VIIRS point; largest of 42 null looks was 183 px',42,'+26 h; confirmed on a second orbit at +62 h'),
  R('Fujairah 3 Mar: S2 differencing','miss (peak z 4.3 < threshold 5)',154,'burned tanks visible by eye'),R('Fujairah 14 Mar','no detection on any method',None),R('Ras Laffan 18/19 Mar: S2 hot pixels','16 px novel cluster at +13 h through 97% cloud, p=0.04, on pre-existing small flare sites',25,'ambiguous: reads as emergency flaring'),
  R('Ras Laffan 18/19 Mar: S2 differencing / S1','no / no (15-37 placebo blobs per look at the observed size)',87,'first clear optical scene +30.6 d'),R('South Pars 18 Mar: S2 hot pixels','17 px vs clear-scene null p95 16, max 294; p~0.06',50,'ambiguous'),R('South Pars 18 Mar: S2 differencing','one 7 px blob 237 m from Refinery 4, peak z 24.6; 9.0 placebo blobs per pair by size alone',197,'ambiguous; mechanical rule said yes, reviewed down'),R('South Pars: S1','no on three orbits',29),
  R('S2 flare activity ratio vs pre-war (scenes <20% cloud): Ras Laffan / Tehran / South Pars','0.40-0.50 / 0.29-0.37 / 0.67',None,'Ras Laffan rests on 1 then 2 clear scenes; independently supports the VIIRS Qatar decline'),R('4-vs-4 S1 stack detector','uninformative',None,'260-2,900 blobs per null window at 3 dB')],
 'controls':'Placebo scene pairs / null looks per site and orbit; blind site-wide ranking; mechanical and reviewed verdicts both stored.','verdict':'rejected','known_or_novel':'known methods; result specific to this war','prior_art':['https://www.hrw.org/news/2026/04/22/israel-iran-unlawful-march-attacks-on-energy-infrastructure','https://en.wikipedia.org/wiki/2026_South_Pars_field_attack'],
 'figures':[B+f's2s1_out/panel_{s}.png' for s in ['ras_laffan','south_pars','fujairah','tehran']]+[B+'s2s1_out/flare_timeseries_s2.png',B+'s2s1_out/zoom_tehran_35.5415_51.4325.png',B+'s2s1_out/zoom_fujairah_25.1850_56.3520.png'],'scripts':sorted(glob.glob(B+'s2s1_*.py')),
 'caveats':'Detector design was iterated after seeing data (three versions of the differencing, threshold picked from a sweep); only results that survive every variant are called detections. Tehran S1 null is inadequate (one null look). Coherence needs SLC, not available anonymously as COG. VH, Landsat and the June 2025 South Pars strike were not analysed.'})
F.append({'id':'flare_leads_prices','title':'Do flare changes lead oil prices, spreads or tanker equities?','one_liner':'No. Round 1: Brent leads the flare index by a day, permutation p=0.20, differenced r=-0.23; the markets agent then ran 46 pre-registered tests with a 10,000-draw max-stat permutation and FDR and none survived.',
 'datasets':[DS['gibs'],DS['px']],'mechanism':'Physical shut-ins would have to be visible from orbit before the market prices them; with 2 looks a day and a market that trades headlines, they are not.','method':'Round 1: lagged correlation and circular-shift permutation (repo stats.py) of log((Basra+Qatar)/(Kirkuk+Oman)) 7-day flare index vs Brent, TTF, GDELT Hormuz share, 15 Jan-15 Jul 2026. Markets agent: pre-registered max-stat permutation with FDR across 46 market tests (reported to us, not rerun here).',
 'results':[R('Brent level r at best lag',-0.76,None,'lag -1 day: Brent leads; permutation p=0.20'),R('Brent 5-day-difference r',-0.23,None),R('TTF level r / differenced r','-0.65 / -0.24',None,'level p=0.002 is one regime shift'),R('half-move dates: Basra flares / Brent','5 Mar / 6 Mar 2026',None),R('market tests surviving FDR (markets agent)','0 of 46',46,'not reproduced by us')],
 'controls':'Differencing; circular-shift permutation; pre-registration and FDR (markets agent).','verdict':'rejected','known_or_novel':'known','prior_art':[],'figures':[B+'flare_vs_brent_gdelt.png'],'scripts':[B+'leadlag.py'],'caveats':'One war, one regime shift: effective n is about 1. Framing should stay on production measurement, not price prediction.'})
F.append({'id':'keyless_viirs_access','title':'Keyless daily VIIRS active-fire points for any place and date since 2012','one_liner':'NASA GIBS vector tiles return full FIRMS attribute rows with no key or login and match FIRMS exactly; this is the only keyless route to 2025-2026 hotspots.',
 'datasets':[DS['gibs'],DS['firms']],'mechanism':'GIBS serves the FIRMS point product as Mapbox vector tiles for visualisation; the tiles retain lat, lon, FRP, time, satellite, confidence.','method':'Decode .mvt tiles at zoom 3-5, dedupe; compare with a Wayback-archived FIRMS 7-day shapefile for 13-20 Mar 2026.',
 'results':[R('detections in Gulf bbox on 2026-03-18: GIBS z=3 vs FIRMS',"877 vs 877",None,'exact'),R('Gulf 2025-01..2026-09, 3 satellites','2.58M detections, 1,881 tile-days, ~4 min, 130 MB',None),R('Bakken+Permian 2012-2026 SNPP','10,700 tile-days',None),R('schema drift','pre-2020 tiles lack DAYNIGHT and use YYYY/MM/DD dates',None,'handled in flarelib.load_gibs'),R('FIRMS country archive','2012-2024 OK; 2025 and 2026 -> 404; API -> Invalid MAP_KEY',None)],
 'controls':'Cross-check against FIRMS file.','verdict':'supported','known_or_novel':'novel as a data-access route (not documented as a bulk source)','prior_art':[],'figures':[],'scripts':[B+'gibs.py',B+'fetch_war_window.py',B+'fetch_us_basins.py'],'caveats':'Visualisation service, not an official bulk API: be polite with request rates. Higher zooms duplicate points across tile buffers (dedupe on lat/lon/date/time/satellite).'})
F.append({'id':'snpp_outage_qa','title':'Do the validations lean on satellite outage weeks?','one_liner':'No. Suomi-NPP was dark 27 Jul-10 Aug 2022 and for five shorter windows in 2024-2026; the country pipeline already excluded those days, the US pipeline did not and was fixed, and every headline statistic moves by less than 0.07 when outage months are removed.',
 'datasets':[DS['firms'],DS['gibs']],'mechanism':'An outage scored as zero detections fakes a simultaneous collapse across all regions.','method':'Per-satellite daily detection counts summed over 16 countries (2012-2024) and over the Gulf pull (2025-26, all three satellites); day flagged if zero or under 25% of a 31-day rolling median; flagged days +-1 removed; months under 15 valid days dropped; headline stats recomputed with every outage-touching month removed.',
 'results':[R('SNPP outage windows >=3 days','2022-07-27..08-10 (15 d), 2024-05-30..06-03, 2024-07-10..15, 2024-07-24..28, 2024-11-03..05, 2026-07-11..15',None,'51 bad days in total; NOAA-20 and NOAA-21 have no window >=3 days in 2025-26'),
  R('Bakken r (YoY / deseason) all months -> outage months removed',f"{ob['bakken']['all_months']['yoy_dlog']} / {ob['bakken']['all_months']['deseason_detrend']} -> {ob['bakken']['outage_months_removed']['yoy_dlog']} / {ob['bakken']['outage_months_removed']['deseason_detrend']}",None),
  *[R(f'{c} YoY r all -> outage months removed',f"{ob[c]['yoy_all']} -> {ob[c]['yoy_outage_months_removed']}",None) for c in ['Libya','Iraq','Iran','Yemen','Algeria']],R('Libya monthly FRP Jul / Aug 2022 (MW) in our series','186 / 498',None,'no mid-2022 collapse once outage days are excluded rather than zero-filled'),R('2026-03-19 low count on all three satellites','~200 vs ~800',None,'region-wide cloud, not an outage')],
 'controls':'Before/after comparison stored in data/*_pre_outage_mask.json.','verdict':'supported','known_or_novel':'known (SNPP anomaly documented by NASA/NOAA)','prior_art':[],'figures':[],'scripts':[B+'outage_check.py',B+'outage_robustness.py',B+'flarelib.py'],'caveats':'Partial-coverage days between 25% and 100% of normal are only caught by the +-1 day buffer. Anyone zero-filling GIBS tile days will see the fake collapse.'})
F.append({'id':'tehran_night_lights','title':'Tehran dimmed for weeks during the war (keyless night lights)','one_liner':'Share of Tehran pixels at DNB saturation fell from 0.60 pre-war to 0.10 in war weeks 3-6 and recovered to 0.44 in the ceasefire, but smoke, cloud and blackout cannot be separated and the keyless imagery saturates at 38 nW.',
 'datasets':[DS['dnb']],'mechanism':'Grid damage or load-shedding reduces upward radiance.','method':'GIBS WMS PNG inverted through the published colormap; fraction of city pixels in the top bin, nightly; Kyiv Nov 2022 blackout as a positive control (round 1, not extended in round 2).',
 'results':[R('Tehran saturated-pixel share: pre-war / war wk1-2 / wk3-6 / ceasefire','0.60 / 0.24 / 0.10 / 0.44',106,'nights'),R('Kyiv lit-pixel share: pre-campaign vs 23-27 Nov 2022','0.39 vs 0.008',139,'single cloudy nights also reach ~0; 23 Nov was a new moon')],
 'controls':'Positive control only; no cloud mask applied.','verdict':'partial','known_or_novel':'known (Black Marble blackout studies)','prior_art':[],'figures':[B+'asset_events.png'],'scripts':[B+'dnb.py'],'caveats':'Black Marble VNP46A2 (moon- and cloud-corrected) needs an Earthdata login, which we did not use.'})
allf=core+F; json.dump(allf,open(B+'findings.json','w'),indent=1,default=str)
print(len(allf),'findings;',{v:sum(1 for f in allf if f['verdict']==v) for v in ['supported','partial','rejected']})
import os; missing=[p for f in allf for p in f['figures']+f['scripts'] if not os.path.exists(p)]; print('missing paths:',missing)
