"""Assemble findings.json from result files (numbers are read from outputs, not retyped, wherever a machine-readable output exists)."""
import json, pandas as pd, numpy as np, os
B='/Users/tomalmog/projects/kingdom/explore/wardamage/'
J=lambda p: json.load(open(B+p)); C=lambda p: pd.read_csv(B+p)
bk,pm,iv,ia=J('data/bakken_validation.json'),J('data/permian_validation.json'),J('data/intl_validation.json'),J('data/intl_asymmetry.json')
cn=C('data/cloud_normalised_flare_table.csv').set_index('region'); al=C('data/alarm_latency.csv'); war=C('data/war2026_prediction_vs_actual.csv'); cond=C('data/intl_conditional_calibration.csv'); ne=C('data/intl_natural_experiments.csv')
cc=C('data/intl_country_correlations.csv').set_index('country'); diag=C('data/cloud_detection_diagnostic.csv'); bcn=pd.read_csv(B+'data/bakken_cloudnorm_comparison.csv',index_col=0)
sb=J('score_out/scoreboard_summary.json') if os.path.exists(B+'score_out/scoreboard_summary.json') else {}
DS={'gibs':{'name':'NASA GIBS WMTS vector tiles: VIIRS 375 m thermal anomalies (SNPP/NOAA-20/NOAA-21)','url':'https://gibs.earthdata.nasa.gov/wmts/epsg4326/best/VIIRS_NOAA20_Thermal_Anomalies_375m_All/default/{date}/500m/{z}/{row}/{col}.mvt','access':'keyless'},
 'firms':{'name':'NASA FIRMS country-year archive CSVs (VIIRS SNPP 2012-2024)','url':'https://firms.modaps.eosdis.nasa.gov/data/country/viirs-snpp/{year}/viirs-snpp_{year}_{Country}.csv','access':'keyless (2025+ not published; API needs MAP_KEY)'},
 'cloud':{'name':'NASA GIBS WMS VIIRS night clear-sky confidence (SNPP 2012+, NOAA-20 2018+)','url':'https://gibs.earthdata.nasa.gov/wms/epsg4326/best/wms.cgi?LAYERS=VIIRS_NOAA20_Clear_Sky_Confidence_Night','access':'keyless (PNG + published colormap)'},
 'dmr':{'name':'North Dakota DMR monthly gas produced/sold/flared 1990-2026','url':'https://www.dmr.nd.gov/oilgas/stats/Gas1990ToPresent.xls','access':'keyless'},
 'eia_vf':{'name':'EIA natural gas vented & flared by state, monthly','url':'https://www.eia.gov/dnav/ng/xls/NG_PROD_SUM_A_EPG0_VGV_MMCF_M.xls','access':'keyless'},
 'eia_state':{'name':'EIA crude production by state, monthly','url':'https://www.eia.gov/dnav/pet/xls/PET_CRD_CRPDN_ADC_MBBLPD_M.xls','access':'keyless'},
 'eia_intl':{'name':'EIA International bulk file (monthly crude+condensate production by country to 2026-05)','url':'https://www.eia.gov/opendata/bulk/INTL.zip','access':'keyless bulk (API itself needs a key)'},
 'jodi':{'name':'JODI Oil World Database primary CSV','url':'https://www.jodidata.org/_resources/files/downloads/oil-data/world_primary_csv.zip','access':'keyless (gaps: Iraq, Qatar, UAE, Libya missing for 2026)'},
 'gdelt':{'name':'GDELT 2.0 raw 15-minute export files','url':'http://data.gdeltproject.org/gdeltv2/','access':'keyless (DOC API returned HTTP 429)'},
 's2':{'name':'Sentinel-2 L2A COGs via Element84 Earth Search','url':'https://earth-search.aws.element84.com/v1','access':'keyless'},
 's1':{'name':'Sentinel-1 RTC via Microsoft Planetary Computer','url':'https://planetarycomputer.microsoft.com/api/stac/v1','access':'anonymous SAS token'}}
PA={'payne':'https://energynewsbeat.co/crude-oil/iran-appears-to-have-increased-flaring-to-keep-the-oil-and-gas-fields-stable-to-avoid-shut-ins/','econ':'https://github.com/TheEconomist/the-economist-war-fire-model','elvidge':'https://www.mdpi.com/1996-1073/9/1/14','ggfr':'https://www.worldbank.org/en/programs/gasflaringreduction'}
def R(metric,value,n=None,note=''): 
    if isinstance(value,(np.floating,np.integer)): value=float(value)
    return {'metric':metric,'value':value,'n':n,'note':note}
F=[]
def us(b,nm,lab,fid):
    ps=b['pair_stats'][lab]; o=b['oos']
    return {'id':fid,'title':f'{nm}: VIIRS night flare power vs reported flared gas volume','one_liner':f'Satellite flare power tracks officially reported flared volume in the {nm} at annual/seasonally-adjusted scale, but month-to-month changes are mostly noise.',
     'datasets':[DS['gibs'],DS['dmr'] if nm=='Bakken' else DS['eia_vf']],'mechanism':'Flared gas burns at ~1600-2000 K; VIIRS I4/M13 radiance at night gives fire radiative power roughly proportional to flared volume.',
     'method':f'SNPP-only night detections 2012-02..2026-08 from keyless GIBS tiles, 0.02 deg cells lit on >=N nights, monthly statistic of nightly FRP sums; metric variant ({b["selected_variant"]}) chosen on 2012-2018 only; log-log OLS trained 2012-2018, tested 2019+; month fixed-effects variant; rolling-origin yearly refits vs a persistence baseline.',
     'results':[R('r log-levels (monthly)',ps['levels_log'][0],ps['n']),R('r month-over-month dlog',ps['mom_dlog'][0],ps['mom_dlog'][2],'weak'),R('r year-over-year dlog',ps['yoy_dlog'][0],ps['yoy_dlog'][2]),R('r deseasonalised+detrended',ps['deseason_detrend'][0],ps['n']),
       R('annual r (log levels)',o['annual_r_loglevel'],o['n_years']),R('annual r (dlog)',o['annual_r_dlog'],o['n_years']-1),R('out-of-sample R2 2019+ (plain)',o['test_R2_model'],o['n_test']),R('out-of-sample R2 2019+ (month FE)',o['test_R2_monthFE'],o['n_test']),
       R('rolling-origin MAPE % model vs persistence',f"{o['rolling_MAPE_model_%']} vs {o['rolling_MAPE_persistence_%']}",None,'barely beats persistence' if nm=='Bakken' else ''),R('elasticity (log label on log FRP)',o['elasticity_b'],o['n_train'],'attenuated well below 1: FRP is a noisy regressor')],
     'controls':'Train/test split in time; metric variant chosen on train only; persistence baseline; deseasonalising and differencing reported alongside levels.','verdict':'partial','known_or_novel':'known (VIIRS Nightfire literature calibrates flare radiant heat to volume); the keyless replication and the honest monthly-change null are ours',
     'prior_art':[PA['elvidge'],PA['ggfr']],'figures':[B+f'fig_{nm.lower()}_validation.png'],'scripts':[B+'gibs.py',B+'fetch_us_basins.py',B+'labels_build.py',B+'flarelib.py',B+'us_validate.py'],
     'caveats':'State-level label vs basin bbox; Texas V&F is operator-reported and lagged; FIRMS FRP is not Nightfire radiant heat (no temperature fit); satellite series carries a 4-7x seasonal artifact absent from the label.'}
F.append(us(bk,'Bakken','ND DMR flared (MCF/d)','us_bakken_flared_volume')); F.append(us(pm,'Permian','EIA TX+NM vented&flared (MMcf/d)','us_permian_flared_volume'))
bc,pc=bk['pair_stats']['EIA ND crude (kb/d)'],pm['pair_stats']['EIA TX+NM crude (kb/d)']
F.append({'id':'us_flare_vs_crude_production','title':'US shale: flare power as a gauge of crude production','one_liner':'In US shale basins flare power says almost nothing about monthly crude output; flaring is driven by gas-takeaway constraints, not barrels.',
 'datasets':[DS['gibs'],DS['eia_state']],'mechanism':'Hypothesis: more oil -> more associated gas -> more flaring. In practice flaring depends on pipeline/processing capacity and regulation.','method':'Same monthly SNPP metrics vs EIA state crude production (ND; TX+NM).',
 'results':[R('Bakken r MoM dlog',bc['mom_dlog'][0],bc['mom_dlog'][2]),R('Bakken r YoY dlog',bc['yoy_dlog'][0],bc['yoy_dlog'][2]),R('Bakken r log-levels',bc['levels_log'][0],bc['n']),R('Permian r MoM dlog',pc['mom_dlog'][0],pc['mom_dlog'][2],'zero'),R('Permian r YoY dlog',pc['yoy_dlog'][0],pc['yoy_dlog'][2]),R('Permian r deseason+detrend',pc['deseason_detrend'][0],pc['n'])],
 'controls':'Differencing and deseasonalising; same pipeline that does track flared volume.','verdict':'rejected','known_or_novel':'known','prior_art':[PA['ggfr']],'figures':[B+'fig_bakken_validation.png',B+'fig_permian_validation.png'],'scripts':[B+'us_validate.py'],'caveats':'State production is not basin production; YoY correlations of 0.3-0.5 reflect the shared 2014-16 and 2020 cycles, not a usable gauge.'})
F.append({'id':'cloud_mask_normalisation','title':'Does clear-sky normalisation rescue the gauge? (tested against a gold label)','one_liner':'Per-cell clear-sky normalisation barely improves fit to reported flared volume, and the satellite series has a 4-7x seasonal swing that cloud does not explain; strict clear-sky filters are biased because flares themselves lower clear-sky confidence.',
 'datasets':[DS['gibs'],DS['cloud'],DS['dmr']],'mechanism':'Cloud blocks the 4 micron signal, so detections should scale with observation opportunity.','method':'Nightly SNPP clear-sky-confidence grids (5,297 nights) sampled at active Bakken flare cells; monthly FRP divided by observable fraction (conf>0.05), by strict clear fraction (conf>=0.95), and clear-nights-only; compared to ND DMR flared volume. Gulf: P(detect) by confidence bin at 1,177 persistent NOAA-20 flare cells.',
 'results':[R('Bakken r MoM dlog raw -> best normalised',f"{bcn.loc['raw_mean','mom_dlog']} -> {bcn[['mom_dlog']].max().iloc[0]}",int(bcn.loc['raw_mean','n'])),R('Bakken r deseason+detrend raw -> conf>=0.95 normalised',f"{bcn.loc['raw_mean','deseason_detrend']} -> {bcn.loc['norm_clear95','deseason_detrend']}",int(bcn.loc['raw_mean','n'])),
   R('seasonal amplitude of satellite series (max/min month) raw / normalised / label','6.7 / 9.6 / 1.18',None,'observable fraction is HIGHER in winter when FRP is lowest, so cloud is not the cause'),
   *[R(f"Gulf P(detect) at clear-sky conf {r.conf_bin}",r['P(detect)'],None,f"share of cell-nights {r.share_of_cell_nights}, mean FRP {r.mean_FRP} MW") for _,r in diag.iterrows()]],
 'controls':'Gold label (ND DMR); same overpass for detections and mask.','verdict':'rejected','known_or_novel':'novel (small): the cloud mask is contaminated by the target - detection probability and FRP peak at intermediate confidence, only conf<=0.05 suppresses detection',
 'prior_art':[],'figures':[B+'fig_cloud_normalised_regions.png'],'scripts':[B+'cloud_fetch.py',B+'cloud_fetch_bakken.py',B+'us_cloudnorm.py',B+'cloud_norm.py'],'caveats':'Cloud mask over snow at night is itself unreliable; cause of the seasonal artifact not identified (candidates: background temperature, summer twilight at 48N, atmospheric transmission). Use YoY or month fixed effects instead.'})
hi,lo=ia['high_intensity'],ia['low_intensity']
F.append({'id':'intl_flare_vs_production','title':'Country-month flare power vs crude production, 16 countries 2012-2024','one_liner':'Flare power tracks production only where routine associated-gas flaring is heavy and the production move is a collapse (Libya, Yemen, Iran, Iraq); in low-flaring-intensity producers (Saudi, Kuwait, UAE, Qatar, Oman) the correlation is zero.',
 'datasets':[DS['firms'],DS['eia_intl'],DS['jodi']],'mechanism':'Routine flaring of associated gas scales with oil lifted; where gas is captured, flares are safety/process flares unrelated to output.','method':'SNPP night detections in persistent flare cells (>=24 nights, >=180-day span) per country, monthly mean nightly FRP, SNPP outage days removed; vs EIA monthly crude. Quarterly non-overlapping YoY dlog panel; country-cluster bootstrap; mismatched-country placebo; split by flaring intensity (FRP per kb/d, chosen ex ante at 0.25).',
 'results':[R('pooled r, quarterly YoY dlog',iv['pooled_all']['r'],iv['pooled_all']['n']),R('pooled slope (95% CI, country-cluster bootstrap)',f"{iv['pooled_all']['slope']} {iv['pooled_all']['slope_ci95_cluster_boot']}",16,'CI nearly touches zero: a handful of countries carry it'),R('placebo r (mismatched country), mean / p95',f"{iv['placebo_mismatched_country']['mean_r']} / {iv['placebo_mismatched_country']['p95_r']}",1000,f"p={iv['placebo_mismatched_country']['p_value_true_r']}"),
   R('high-intensity countries r / leave-one-country-out R2',f"{hi['r']} / {hi['LOCO_R2']}",hi['n'],', '.join(ia['high_intensity_countries'])),R('low-intensity countries r',lo['r'],lo['n'],'no information'),
   *[R(f'{c} r YoY dlog (monthly)',cc.loc[c,'yoy_dlog'],int(cc.loc[c,'n'])) for c in ['Libya','Yemen','Iran','Iraq','Nigeria','Venezuela','Kazakhstan','Algeria','Saudi_Arabia','Kuwait','United_Arab_Emirates','Qatar','Oman']],
   R('Spearman(country r, flaring intensity) / (country r, production volatility)',f"{iv['where_it_works']['spearman(r, flaring_intensity)']} / {iv['where_it_works']['spearman(r, production_volatility)']}",16,'label variance explains where it works at least as well as intensity')],
 'controls':'Changes not levels; placebo; clustered bootstrap; leave-one-country-out.','verdict':'partial','known_or_novel':'known in outline (World Bank GGFR/Payne use VIIRS for flaring volumes); the production-gauge validity map by country is not something we found published',
 'prior_art':[PA['ggfr'],PA['elvidge'],PA['payne']],'figures':[B+'fig_intl_calibration.png'],'scripts':[B+'fetch_firms_countries.sh',B+'fetch_firms_rev.sh',B+'intl_build.py',B+'intl_validate.py',B+'intl_asymmetry.py'],
 'caveats':'FIRMS country files are land-only (offshore flares missing: Nigeria, UAE, Qatar, Angola hurt); Russia and Angola not tested (download size); EIA monthly figures for Venezuela/Syria/Libya are themselves estimates; Syria and Venezuela show production collapse with flat flaring.'})
F.append({'id':'natural_experiments','title':'Named natural experiments: does flaring fall when production is knocked out?','one_liner':'Sustained collapses show up nearly 1:1 (Libya 2020 -89%/-89%, Yemen 2015 -90%/-90%, Iran sanctions -41%/-30%), managed OPEC+ cuts do not, and acute outages at gas-handling-heavy producers make flaring go UP (Abqaiq +122%, Kazakhstan +44%/+305%).',
 'datasets':[DS['firms'],DS['eia_intl']],'mechanism':'Shut-in wells stop flaring; but when processing/export infrastructure trips while wells keep flowing, gas is diverted to flare.','method':'21 pre-specified (country, pre-window, event-window) episodes; % change in mean monthly flare FRP vs % change in EIA production.',
 'results':[R('episodes with same sign',iv['named_experiments']['same_sign_all'],iv['named_experiments']['n']),R('same sign among |dP|>=15%',iv['named_experiments']['same_sign_big'],iv['named_experiments']['n_big(|dP|>=15%)']),R('r of log changes',iv['named_experiments']['r_dlog'],iv['named_experiments']['n']),
   *[R(f"{r.country} {r.episode}: production % / flare %",f"{r['prod_change_%']} / {r['flare_change_%']}",None,'same sign' if r.same_sign else 'OPPOSITE sign') for _,r in ne.iterrows()]],
 'controls':'Windows fixed before looking at flare data; all episodes reported including failures.','verdict':'partial','known_or_novel':'known for Libya/Yemen-type collapses; the sign flip for acute outages is documented anecdotally (Payne 2026: Iran flaring up)','prior_art':[PA['payne'],PA['ggfr']],
 'figures':[B+'fig_intl_calibration.png'],'scripts':[B+'intl_validate.py'],'caveats':'Short windows are not seasonally controlled; Venezuela (-77% production, flat flaring) and Syria (-85%, flat) are outright failures of the gauge; n=21.'})
F.append({'id':'calibration_drop_to_production','title':'Given an X% flare drop sustained for a quarter, what production change does history imply?','one_liner':'Only flare drops deeper than ~50% carry information (median production -36%, but 10th-90th percentile -88%..+16%); drops of 15-50% imply a median production change of about -1%. The pooled calibration failed out-of-sample on the 2026 war.',
 'datasets':[DS['firms'],DS['gibs'],DS['eia_intl']],'mechanism':'Empirical calibration of d log(production) on d log(flare FRP).','method':'752 country-quarters (16 countries, 2013-2024) of YoY changes; conditional distributions by flare-change bin; pooled OLS with residual-sd prediction interval; then applied, untouched, to Mar-May 2026 vs Mar-May 2025 for 7 Gulf producers and compared with EIA actuals.',
 'results':[*[R(f"flare YoY {r.flare_YoY_change_bin}: median production % (p10..p90)",f"{r['median_prod_change_%']} ({r['p10_%']}..{r['p90_%']})",int(r.n_country_quarters),f"{int(r.n_countries)} countries; P(prod down>10%)={r['share_prod_down_>10%']}, P(down>30%)={r['share_prod_down_>30%']}") for _,r in cond.iterrows()],
   R('pooled slope / resid sd (log points)',f"{iv['pooled_all']['slope']} / {iv['pooled_all']['resid_sd']}",iv['pooled_all']['n']),R('2026 out-of-sample: actuals inside 80% PI',iv['war2026']['PI_coverage'],iv['war2026']['n'],'should be ~0.8'),R('2026 Spearman(flare change, actual production change)',iv['war2026']['spearman'],iv['war2026']['n']),
   *[R(f"2026 {r.country}: flare YoY % -> predicted % [80% PI] vs actual %",f"{r['flare_YoY_%']} -> {r['pred_prod_%(pooled)']} [{r['pred_80%PI']}] vs {r['actual_prod_YoY_%(EIA)']}",None,'inside PI' if r.actual_in_PI else 'OUTSIDE PI') for _,r in war.iterrows()],
   *[R(f"2026 {w['country']} with high-intensity-only calibration (exploratory)",f"pred {w['pred_%']}% [{w['PI80']}] vs actual {w['actual_%']}%",None,'post-hoc subset, n=2') for w in ia['war2026_high_intensity_only']]],
 'controls':'Calibration frozen on <=2024 data; 2026 labels (EIA INTL to 2026-05) never used in fitting.','verdict':'rejected','known_or_novel':'novel (the negative result and the conditional table)','prior_art':[PA['payne']],'figures':[B+'fig_intl_calibration.png'],'scripts':[B+'intl_validate.py',B+'intl_asymmetry.py'],
 'caveats':'The deep-drop bin is 26 quarters from 6 countries (mostly Libya and Yemen). Honest product statement: a >50% sustained drop in a heavy-flaring country means a major outage with ~60% probability of >10% production loss; nothing finer.'})
g=lambda r,k: cn.loc[r,k]
F.append({'id':'gulf2026_clear_sky_robustness','title':'2026 Hormuz closure: which regional flare collapses survive clear-sky normalisation?','one_liner':'Basra (-65% YoY) and Qatar (-53%) survive per-cell clear-sky normalisation with non-overlapping bootstrap intervals; the round-1 drops for Saudi-East and Kuwait were cloud artifacts and vanish.',
 'datasets':[DS['gibs'],DS['cloud'],DS['eia_intl']],'mechanism':'Iraq had no export route and shut in; Qatar halted LNG; less lifted oil/gas -> less routine flaring.','method':'NOAA-20 night detections at 1,177 persistent flare cells; per-cell baseline mean FRP on observable nights; index = observed/expected over observable cell-nights only; closure window 4 Mar-8 Apr 2026 vs same weeks 2025 and vs Dec-Feb; weekly block bootstrap; 3 control regions.',
 'results':[*[R(f"{r}: closure index [95% CI] vs same weeks 2025 [CI]; YoY %",f"{g(r,'closure_ratio')} [{g(r,'closure_ci')}] vs {g(r,'same_weeks_2025_ratio')} [{g(r,'same_weeks_2025_ci')}]; {g(r,'closure_vs_2025same_%')}%",int(g(r,'n_cells')),f"raw (unnormalised) YoY {g(r,'RAW_closure_vs_2025same_%')}%; observable share {g(r,'closure_clearfrac')} vs {g(r,'same_weeks_2025_clearfrac')}") for r in cn.index],
   R('EIA actual production Mar-May 2026 YoY: Iraq / Qatar / Kuwait / Saudi / UAE',' / '.join(str(war.set_index('country').loc[c,'actual_prod_YoY_%(EIA)']) for c in ['Iraq','Qatar','Kuwait','Saudi_Arabia','United_Arab_Emirates']),None,'flaring fell only where routine flaring dominates')],
 'controls':'Control regions (Kirkuk, Oman, Turkmenistan); same-weeks-prior-year; observation-opportunity normalisation; block bootstrap.','verdict':'supported','known_or_novel':'known (Payne Institute published the regional flaring decline for this war); the clear-sky robustness check and the Saudi/Kuwait correction are ours',
 'prior_art':[PA['payne']],'figures':[B+'fig_cloud_normalised_regions.png',B+'flare_proxy_regions.png'],'scripts':[B+'cloud_fetch.py',B+'cloud_norm.py',B+'flare_proxy.py'],'caveats':'March 2026 was cloudier than March 2025 over Basra (observable share 0.32 vs 0.50). One year of baseline only. The normalisation uses conf>0.05 because stricter cuts are biased (see cloud_mask_normalisation).'})
ba=al[(al.region=='Iraq-Basra')]; qa=al[al.region=='Qatar']
F.append({'id':'alarm_latency','title':'How fast does the flare gauge flag a regional shut-in, and how often does it cry wolf?','one_liner':'A 7-day clear-sky-normalised alarm fired for Basra 7 days after the war began (10 days for the 14-day window) and stayed on for 84-91% of the closure; controls fired 0-5% of the time; Kuwait, Saudi and UAE never alarmed despite 25-70% production losses.',
 'datasets':[DS['gibs'],DS['cloud']],'mechanism':'as above','method':'Alarm = N-day normalised index below the 2nd percentile of its own Jan 2025-Feb 2026 distribution; count distinct baseline alarm episodes as false alarms.',
 'results':[*[R(f"{r.region} {r.window_days}d: days after war start / baseline alarm episodes / share of war days in alarm",f"{r.days_after_war_start} / {r.baseline_alarm_episodes} / {r.share_war_days_in_alarm}",None,f"threshold {r.threshold_ratio}") for _,r in al[al.region.isin(['Iraq-Basra','Qatar','Kuwait','Saudi-East','UAE','CTRL Oman','CTRL Iraq-Kirkuk/Kurdistan'])].iterrows()]],
 'controls':'Threshold set on pre-war data only; control regions.','verdict':'partial','known_or_novel':'novel (operational characterisation)','prior_art':[],'figures':[B+'fig_cloud_normalised_regions.png'],'scripts':[B+'alarm_latency.py'],'caveats':'2nd-percentile threshold by construction fires ~2% of baseline days (2-6 episodes in 14 months). The 10 Mar "6.7 mb/d offline" headline came 3 days after the first Basra alarm, but prices had already moved (round 1: Brent half-move 6 Mar).'})
json.dump(F,open(B+'findings_core.json','w'),indent=1,default=str); print(len(F),'core findings written')
