"""Freeze NBA approximation amendment before statistical testing."""
import json,hashlib,datetime
from pathlib import Path
R=Path(__file__).resolve().parents[2]
p=R/'amendment_nba_v1.json'
if p.exists():raise SystemExit('Amendment already frozen')
tests=[]
def add(id,signal,target,transform,mechanism,sign='positive',**kw):
 tests.append(dict(id=id,signal=signal,target=target,transform=transform,expected_sign=sign,mechanism=mechanism,horizons_hours=[24],**kw))
for h in [24,6,1]:
 for metric in ['brier','logloss','blend_brier']:
  add(f'{metric}_{h}h','past resolved NBA fills-only PnL >10000; >=10 prior games; >=3 experts; PnL x net shares weighted holdings',metric+' market loss minus expert/blend loss','paired per-game loss difference','Category skill improves predictions',horizon=h)
for threshold in ['1000','5000','50000','top25','top10percent']:
 add('threshold_'+threshold,'qualification '+threshold,'Brier improvement','paired per-game loss difference','Skill robust to cutoff',variant='threshold_'+threshold)
for v in ['equal','pnl','size','roi_shrunk','hit_rate_shrunk']:
 add('weight_'+v,v+' weighting','Brier improvement','paired per-game loss difference','Skill robust to aggregation',variant='weight_'+v)
for v in ['minpast5','minpast20','include_mm','exclude_top3','liquidity_low','liquidity_mid','liquidity_high','complete_pair_expost']:
 add('robust_'+v,v,'Brier improvement','paired per-game loss difference','Composition and sample sensitivity',variant=v)
add('persistence_rank','training category PnL','test-period category PnL','Spearman correlation; permutation of future PnL across wallets','Persistent skill')
add('persistence_decile','training category PnL deciles','test-period PnL','top minus bottom decile mean future profit; wallet bootstrap','Persistent skill')
for k in range(10):
 add(f'placebo_{k:02d}','random wallets matched by past activity and traded notional quintiles','Brier improvement','paired per-game difference','Random matched wallets should not outperform',sign='zero',seed=4100+k)
add('outcome_divergence','expert-minus-market probability','resolution outcome','train logistic correction of logit market by divergence; heldout logloss improvement','Incremental information')
add('drift_max','expert-minus-market probability','next 1/6/24h price changes','studentized signed drift covariance, max-statistic sign flip over horizons','Prices move toward expert view',horizons_search=[1,6,24])
add('economic_2c','direction of expert-minus-market divergence','resolution payoff net of last-price entry and 2c all-in cost allowance','mean signed outcome-price minus 0.02; bootstrap by game','Approximate gross relationship survives illustrative costs')
a={
 'created_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'original_prereg_sha256':hashlib.sha256((R/'prereg.json').read_bytes()).hexdigest(),
 'authorization':'User explicitly requested approximate NBA fills-only reconstruction, negative-inventory exclusions and actual tests; original completeness gates superseded for this amendment only.',
 'primary_test':'brier_24h','family_size':len(tests),'family':tests,
 'scope':'NBA full-game moneyline markets only, exact nba-TEAM-TEAM-YYYY-MM-DD slug; exclude WNBA, NCAA, props, futures, totals and handicaps. Gamma cached vol10k universe implies final-volume selection bias.',
 'primary_period':{'warmup_start':'2024-04-01','train_end':'2025-01-01','holdout_start':'2025-01-02','holdout_end':'2025-07-01','note':'Full 2024/25 season coverage; calendar split fixed before performance analysis. No threshold tuning.'},
 'v2_extension':'Extract only mapped NBA tokens in V2 coverage from 2026-04-28 onward. Report separately as a coverage extension, not pooled primary inference because intervening 2025/26 histories are not guaranteed complete. No V2 forecast claims unless all selected games have complete fill coverage.',
 'extraction':'Pinned HF V1/V2 revisions; remote parquet token predicate and projected columns, cached NBA-only rows. Column chunks may contain non-NBA rows internally; do not download/save full universe files. Bound files by market creation/resolution overlap and record every partition scanned.',
 'ledger':{'perspective':'maker field only in each OrderFilled, including taker-order maker aggregate rows; never synthesize opposite taker row','v1_fees':'BUY reduces received shares, SELL reduces collateral proceeds','v2_fees':'BUY adds collateral cost; SELL reduces collateral proceeds','net_inventory':'signed shares per wallet/token, strict chronological block/log replay','negative_policy':'At signal t drop a wallet-market pair if either outcome inventory has ever fallen below -1e-6 up to t. For realised history drop if ever negative through resolution. Never use a future violation to clean an earlier primary signal. Also report full-path ever-negative counts and an explicitly ex-post-cleaned sensitivity (selection leakage disclosed).','pnl':'cash flows through resolution plus remaining outcome shares at metadata payout, included once only after resolution timestamp < t. No transfers/splits/merges/redemptions/conversions/proxy mapping; histories are sample-period NBA PnL, not lifetime overall PnL.','resolution':'Gamma closedTime proxy; no payout-finality proof. Use terminal 0/1 prices with tolerance 1e-4. Exclude ambiguous/void outcomes.'},
 'signal':{'primary_threshold':10000,'min_prior_resolved_games':10,'min_experts':3,'probability':'weighted mean of token0 inventory/(token0+token1 inventory); team0 rather than literal YES','weight':'positive past NBA PnL times total net outcome shares','blend':0.5,'market_price':'last observed execution on either outcome, translated to token0 probability, strictly at/before snapshot; report staleness; up to48h allowed, never future interpolation','market_maker':'as-of t, >=100 fills, buy and sell each >=25% of cumulative dollar volume, dollar turnover/(1+absolute cumulative net cashflow)>10; exclude. Behavior flag only, not known identity/intent.','liquidity':'traded dollar volume strictly before snapshot; tertile cutpoints fitted on train only','shrunk_roi':'positive PnL/(gross buy cost+1000)','shrunk_hit_rate':'(profitable resolved games+5)/(resolved games+10)'},
 'inference':{'resamples':10000,'seed':20260920,'alpha':0.05,'cluster':'unique game market, one outcome0 forecast per horizon','BH':'entire amended family; blocked tests conservatively p=1 for adjustment, display missing. Original83 ledger is preserved in archive, superseded by this amended family.','primary_bootstrap':'paired event bootstrap with centered two-sided null and percentile95% CI','lag_search':'joint game-level sign flips; max statistic across 1/6/24h','minimum_n':20,'MDE':'(z(1-.05/(2*family_size))+z(.8))*event SD/sqrt(n), conservative80% power','persistence':'training PnL frozen at split; future PnL measured over distinct test games including zero for inactive training wallets; no selecting only future survivors','placebo':'one matched alternative wallet per expert, without replacement where possible; match past activity and dollar-volume quintiles within current eligible holders; fixed seeds; no PnL qualification for placebo','forecast_clip':0.001},
 'economic':'No order simulation. Observed historical spread only if source available. Otherwise report analytical break-even cost in cents and cost sensitivities 1/2/5/10c, no executable profit claim and no invented USD100 depth.',
 'sanity':'Deterministically choose8 addresses spanning training-PnL ranks; compare approximate NBA PnL to public NBA/overall leaderboard if served. Report signed/absolute error and noncomparable coverage, do not require match.',
 'known_limitations':['Unobserved non-fill lifecycle events','Causal negative-inventory exclusion cannot detect all missing flows','Partial category/sample-period PnL is not lifetime skill','Market-maker behavioral proxy may misclassify','Last execution is not midpoint or executable quote','Gamma closedTime is mutable and can lag sporting outcome','Resolution-aligned snapshots are ex-post evaluation clocks','Final-volume-filtered Gamma universe has selection bias','Pre-2024 trade history omitted','Explicit ex-post-cleaned sensitivity can have selection leakage'],
 'nonzero_panel':'Retain all observed game-horizon rows, with missing expert fields if fewer than3 experts; actual tests use the declared eligible subset. Never substitute synthetic probabilities.'}
p.write_text(json.dumps(a,indent=2)+'\n');h=hashlib.sha256(p.read_bytes()).hexdigest();(R/'amendment_nba_v1.sha256').write_text(h+'  '+p.name+'\n');print('amended family',len(tests),h)
