"""Assemble findings.json from results.csv / placebo_results.csv / exploratory_results.csv / case_studies.json so every number is traceable."""
import json, pandas as pd
from pathlib import Path
H = Path(__file__).parent; R = pd.read_csv(H / "results.csv").set_index("id"); PL = pd.read_csv(H / "placebo_results.csv"); E = pd.read_csv(H / "exploratory_results.csv").set_index("id")
CS = json.load(open(H / "case_studies.json")); PW = pd.read_csv(H / "power.csv").set_index("id"); PRE = json.load(open(H / "prereg.json"))
mk, ph = R[R.tier == "market"], R[R.tier == "physical"]; fig = lambda n: str(H / "figures" / n); sc = lambda *n: [str(H / x) for x in n]
def res(i, note=""):
    r = R.loc[i]; return {"metric": f"{i}: r({r.signal}|{r.transform} -> {r.target}) at best lag {int(r.best_lag)}{'m' if r.freq=='M' else 'w'}", "value": round(float(r.r), 3), "n": int(r.n),
                          "note": f"max-stat p={r.maxstat_p:.4f}, BH q={r.bh_q:.3f}, single-lag p={r.perm_p:.4f}, needed |r|>={PW.crit_r_p05[i]:.2f} for p<.05; OOS r_train={r.r_train:+.2f} -> r_test={r.r_test:+.2f} (p={r.p_test:.3f}). {note}".strip()}
DS = {"gww": {"name": "Global Water Watch reservoir surface area (Landsat/Sentinel-2 derived)", "url": "https://api.globalwaterwatch.earth", "access": "keyless REST"},
 "ons": {"name": "Brazil ONS open data: EAR by subsystem (daily), CMO (weekly), energy balance (hourly)", "url": "s3://ons-aws-prod-opendata/dataset/", "access": "anonymous S3"},
 "yf": {"name": "Yahoo Finance daily closes via yfinance", "url": "https://finance.yahoo.com", "access": "keyless"},
 "sina": {"name": "SHFE aluminium main contract AL0 (Sina Finance via akshare)", "url": "https://finance.sina.com.cn/futures/quotes/AL0.shtml", "access": "keyless"},
 "gibs": {"name": "VIIRS S-NPP 375 m thermal anomalies, NASA GIBS vector tiles, daily 2012-01-20..2026-09-18 (5,355 days x 3 tiles)", "url": "https://gibs.earthdata.nasa.gov/wmts/epsg4326/best/VIIRS_SNPP_Thermal_Anomalies_375m_All/", "access": "keyless"},
 "eia930": {"name": "EIA-930 hourly generation by source (PUDL nightly parquet, cached by scout)", "url": "s3://pudl.catalyst.coop/nightly/", "access": "anonymous S3"},
 "glofas": {"name": "GloFAS v4 river discharge via Open-Meteo Flood API (Kaub; Budapest, Saumur placebos)", "url": "https://flood-api.open-meteo.com/v1/flood", "access": "keyless"},
 "nve": {"name": "NVE weekly reservoir filling, Norway 1995-2026", "url": "https://biapi.nve.no/magasinstatistikk/api/Magasinstatistikk/HentOffentligData", "access": "keyless"},
 "eds": {"name": "Nord Pool day-ahead SYS price via Energi Data Service", "url": "https://api.energidataservice.dk/dataset/Elspotprices", "access": "keyless but aggressively rate-limited (429)"}}
METHOD = "Pre-registered (prereg.json, sha256 in data/prereg.sha256) before any signal-target statistic was computed. Signals: expanding-window deseasonalised anomalies (no full-sample statistics), lagged by product latency. Targets: log returns (equities in excess of local index). Statistic: max |Pearson r| over pre-registered lags; null = 10,000 block-permutation+circular-shift surrogates (calibrated on synthetic AR data: 5% false-positive rate); exact circular-shift and year-shuffle nulls as cross-checks; Benjamini-Hochberg across the whole family; 60/40 chronological OOS split; partial-out of commodity index/DXY/Shanghai Composite; placebo reservoirs."
n_run, n_fam = len(R), PRE["family_size"]; plm = PL[PL.tier == "market"]
F = []
F.append({"id": "M0", "title": "Family verdict: orbit-measured physical signals vs liquid market returns", "one_liner": f"{int(mk.survives_bh05.sum())} of {len(mk)} market-tier tests survive BH at q=0.05 (smallest q={mk.bh_q.min():.2f}); the p-value distribution is indistinguishable from the placebo battery.",
 "datasets": [DS[k] for k in ("gww", "gibs", "glofas", "nve", "ons", "yf", "sina", "eia930")], "mechanism": "A physical supply shock visible from orbit (low reservoir, dark flares, low river) should move the price of the constrained commodity or the equity of the exposed producer in the weeks/months after the satellite value becomes knowable.",
 "method": METHOD, "results": [{"metric": "family size pre-registered / run", "value": f"{n_fam} / {n_run}", "n": n_run, "note": "P8 (NVE -> Nord Pool) is the only test that may be missing: Energi Data Service rate-limited the price download" if n_run < n_fam else "all run"},
  {"metric": "market-tier tests with uncorrected max-stat p<0.05", "value": int((mk.maxstat_p < .05).sum()), "n": len(mk), "note": f"expected by chance ~{0.05*len(mk):.1f}; the one hit is F3 (Libya flares -> tanker equities, p={R.maxstat_p['F3']:.3f}, q={R.bh_q['F3']:.2f}); it has no directional prior, its train-period sign is opposite, and it flips sign (r={E.r['E9_TANKERS(FRO,DHT)-^GSPC']:+.3f}) when the flare index is normalised by the Algeria control"},
  {"metric": "market-tier BH survivors (q<=0.05)", "value": int(mk.survives_bh05.sum()), "n": len(mk), "note": "also zero at q<=0.10"},
  {"metric": "median |r| market tier", "value": round(float(mk.r.abs().median()), 3), "n": len(mk), "note": f"median |r| needed for nominal significance {PW.crit_r_p05[mk.index].median():.2f}: effects larger than ~0.15 (n~240) to ~0.25 (n~90) are excluded; smaller ones are not"},
  {"metric": "placebo reservoirs/regions vs the same market targets: share with p<0.05", "value": round(float((plm.maxstat_p < .05).mean()), 3), "n": len(plm), "note": "nominal 0.05 -> the null is calibrated on real data too"}],
 "controls": "After partialling ^SPGSCI/DXY/Shanghai Composite out of the targets the smallest market-tier p is %.3f (F3 again; next %.2f). Year-shuffle and exact circular-shift nulls agree with the block null. Signs match the pre-registered mechanism in %d%% of market tests and train/test signs agree in %d%% - coin flips." % (mk.p_partial.min(), mk.p_partial.nsmallest(2).iloc[-1], round(100 * mk.sign_ok.mean()), round(100 * mk.oos_same_sign.mean())),
 "verdict": "rejected", "known_or_novel": "known in spirit (semi-strong efficiency; Mukherjee et al. 2021 show satellite estimates are already impounded in prices) - the contribution is a clean, pre-registered, keyless replication across 6 physical systems", "prior_art": ["https://www.sciencedirect.com/science/article/abs/pii/S0304405X21000921", "https://www.cambridge.org/core/journals/journal-of-financial-and-quantitative-analysis/article/on-the-capital-market-consequences-of-big-data-evidence-from-outer-space/2F5F99D68D1F8940F61578F198D6C005"],
 "figures": [fig("fig4_family_overview.png"), fig("fig5_lag_profiles.png")], "scripts": sc("prereg_build.py", "signals.py", "targets.py", "engine.py", "test_engine.py", "run_tests.py"),
 "caveats": "Monthly/weekly horizons only; latency assumptions are conservative (1 month for GWW); power is limited for |r|<0.15; equities tested in excess of the local index only; no options/vol or intraday targets; results describe statistical association, not trading advice."})
F.append({"id": "Y", "title": "Yunnan reservoirs from orbit -> aluminium", "one_liner": "Xiaowan+Nuozhadu surface-area anomalies carry no information for SHFE/COMEX aluminium or producer equities at 1-3 months after they are knowable; at 3 of 5 curtailment announcements the knowable anomaly was positive.",
 "datasets": [DS["gww"], DS["sina"], DS["yf"]], "mechanism": "Low Lancang storage -> Yunnan hydro deficit -> smelter curtailment (Yunnan ~12% of Chinese capacity) -> aluminium up, Yunnan Aluminium down, ex-China producers up.", "method": METHOD + " Signal from 2019-01 (both reservoirs impounded by 2014; 3 years of expanding climatology).",
 "results": [res(i) for i in ["Y1_z", "Y1_dz3", "Y2_z", "Y3_dz3", "Y4_z", "Y5_z"]] + [{"metric": "coincident (lag 0, no latency) r, yunnan z vs SHFE_AL [EXPLORATORY]", "value": round(float(E.r["E1_Y1_z"]), 3), "n": int(E.n["E1_Y1_z"]), "note": f"p={E.maxstat_p['E1_Y1_z']:.2f}: the market does not even co-move with the area anomaly"},
  {"metric": "case studies: curtailment announcements (n=5, NOT statistics)", "value": json.dumps([{k: e[k] for k in ("event_month", "z_known_at_event (month m-2)", "shfe_al_ret_prev3m_%", "shfe_al_ret_next3m_%")} for e in CS["yunnan"]]), "n": 5, "note": "2021-05 and 2022-09: knowable z was +1.8 and +1.0; SHFE had already rallied 24% in the 3 months before 2021-05"}],
 "controls": "Partial-out of SPGSCI/DXY/Shanghai Composite leaves r unchanged; 4 placebo reservoirs give the same p-value distribution; scout's earlier informal look (r=0.06, n=144) counted as prior exploration.", "verdict": "rejected", "known_or_novel": "mechanism is well known to metals desks (Reuters/Fastmarkets/SMM cover it in real time); the satellite-to-price null at monthly latency is, as far as we found, not published",
 "prior_art": ["https://www.mining.com/web/column-another-yunnan-power-blow-to-chinas-aluminum-output/", "https://www.fastmarkets.com/insights/yunnan-aluminium-producers-ordered-to-cut-output-amid-power-rationing/", "https://news.metal.com/newscontent/101936979-smm-analysis-of-the-impact-of-power-shortages-in-yunnan-on-chinese-aluminum-supply", "https://www.alcircle.com/news/yunnan-aluminium-industry-is-in-woes-due-to-the-dry-season-with-nearly-400-000-tonnes-of-output-cut-110295"],
 "figures": [fig("fig1_yunnan_aluminium_case_study.png")], "scripts": sc("signals.py", "run_tests.py", "exploratory.py", "figures.py"),
 "caveats": "n=85-90 months: only |r|>~0.22-0.26 was detectable. Monsoon cloud leaves Jun-Sep gaps at Xiaowan. Two multi-year regulating reservoirs are a poor proxy for province-wide inflow; curtailments were also driven by demand growth and energy 'dual-control' policy. Event dates are month-resolution from trade press."})
F.append({"id": "B-phys", "title": "Brazil: satellite reservoir area -> official stored energy -> marginal cost and thermal dispatch", "one_liner": f"A 9-reservoir satellite composite tracks ONS stored energy (3-month changes r={R.r['P1']:+.2f}, OOS {R.r_test['P1']:+.2f}) and explains marginal operating cost nearly as well as the operator's own data (r={R.r['P2']:+.2f} vs {R.r['P4']:+.2f}) - but it is coincident, not predictive, and ONS publishes the truth daily.",
 "datasets": [DS["gww"], DS["ons"]], "mechanism": "SE/CO holds ~70% of Brazilian storage; the dispatch model prices water by storage, so storage down -> CMO (the basis of the PLD spot price) up -> thermal share up.", "method": METHOD + " Physical-link tier: 3-month changes on both sides, lags 0-2 months, latency ignored.",
 "results": [res("P1"), res("P2"), res("P3"), res("P4", "upper bound with official storage"),
  {"metric": "forward prediction of CMO change over the 3 months AFTER the satellite value is knowable [EXPLORATORY]", "value": round(float(E.r["E3_brazil_seco_area_dz3"]), 3), "n": int(E.n["E3_brazil_seco_area_dz3"]), "note": f"p={E.maxstat_p['E3_brazil_seco_area_dz3']:.2f}: no lead. Official EAR z-level -> next-3m CMO change r={E.r['E3_brazil_ear_seco_z']:+.2f} (uncorrected p={E.maxstat_p['E3_brazil_ear_seco_z']:.3f}, positive = mean reversion, not a drought signal)"},
  {"metric": "partial r(satellite, CMO | official EAR) [EXPLORATORY]", "value": round(float(E.r["E2"]), 3), "n": int(E.n["E2"]), "note": "non-zero, but official data has 1-day latency vs ~1 month for GWW, so no usable edge"},
  {"metric": "placebo warning: Toktogul (Kyrgyzstan) area vs Brazil stored energy", "value": 0.342, "n": 214, "note": "p=0.0004 under block, circular and year-shuffle nulls; OOS r=0.17. Likely a shared climate driver (ENSO). Geographic placebos are not independent draws; separate real from placebo by effect size and OOS stability (0.75/0.87 vs 0.34/0.17), not by p alone"}],
 "controls": "4 placebo reservoirs; year-shuffle p=0.0001; exact circular-shift p=0.004 (floor 1/230); OOS holds for all four.", "verdict": "supported", "known_or_novel": "known (storage drives Brazilian power prices by construction of NEWAVE/DECOMP); our add is that a keyless satellite composite recovers ~90% of the official signal's explanatory power - useful only where no ONS-like operator data exists",
 "prior_art": ["https://www.nature.com/articles/s41598-022-17074-6", "https://dados.ons.org.br/"], "figures": [fig("fig2_brazil_storage_cmo_equity.png"), fig("fig5_lag_profiles.png")], "scripts": sc("fetch_ons.py", "signals.py", "targets.py", "run_tests.py", "exploratory.py"),
 "caveats": "CMO is an administratively computed price, not a traded one; overlapping 3-month differences (handled by block null). This validates the sensor, it is not a market signal."})
F.append({"id": "B-mkt", "title": "Brazil reservoir storage -> utility and thermal-generator equities", "one_liner": "No predictive relation from satellite area OR from official ONS stored energy to excess returns of Eletrobras/Axia, Cemig, Engie Brasil, Eneva, Energisa.",
 "datasets": [DS["gww"], DS["ons"], DS["yf"]], "mechanism": "Hydro-long generators lose (GSF deficit) and gas generators gain when storage is low.", "method": METHOD, "results": [res(i) for i in ["B1_z", "B3_z", "B4_dz3", "B5_z", "G1_dz3", "G2_dz3"]],
 "controls": "Upper-bound design: if the operator's own storage series (G1-G3) has no information for next-month returns, no satellite proxy can. Excess over Bovespa; SPGSCI/DXY partial-out.", "verdict": "rejected", "known_or_novel": "not found in prior art as a tested null", "prior_art": ["https://dados.ons.org.br/"],
 "figures": [fig("fig2_brazil_storage_cmo_equity.png")], "scripts": sc("run_tests.py"), "caveats": "Several wrong-signed r around -0.1 (B1_z, B3_z, B5_z) are what mean reversion after crisis sell-offs would produce; none is significant. Yahoo CMIG4 history needed a splice-error fix (daily |log return|>1.5 nulled)."})
F.append({"id": "Z", "title": "Zambia (Itezhi-Tezhi area) -> copper, First Quantum, kwacha", "one_liner": "No relation at 1-3 months; nearest is kwacha vs 3-month area change (r=%.2f, p=%.2f) with zero out-of-sample correlation." % (R.r["Z3_dz3"], R.maxstat_p["Z3_dz3"]),
 "datasets": [DS["gww"], DS["yf"]], "mechanism": "Kafue/Zambezi hydro deficit -> ZESCO load-shedding -> mine output, imports, FX stress.", "method": METHOD + " Kariba excluded a priori: scout showed its area does not track level.", "results": [res(i) for i in ["Z1_z", "Z2_z", "Z3_dz3"]],
 "controls": "HG=F partialled out of USDZMW; placebos.", "verdict": "rejected", "known_or_novel": "mechanism known (2015-16, 2019, 2024 load-shedding); tested null not found", "prior_art": ["https://www.nature.com/articles/s41598-022-17074-6"], "figures": [fig("fig4_family_overview.png")], "scripts": sc("run_tests.py"),
 "caveats": "Zambia is ~3% of world copper, so a price effect was a weak prior. No keyless Eurobond series. USDZMW from Yahoo starts 2013."})
F.append({"id": "U", "title": "US West reservoirs -> hydro/gas generation -> Henry Hub and California utilities", "one_liner": "Price leg null everywhere; the pre-registered 6-reservoir composite does not even track Western-Interconnection hydro (wrong geography: WECC hydro is Columbia-basin), though a California-only composite tracks CAISO hydro (exploratory r=%.2f)." % E.r["E4_z_CISO hydro"],
 "datasets": [DS["gww"], DS["eia930"], DS["yf"]], "mechanism": "Low storage -> less hydro -> more gas burn -> gas price / utility procurement cost and wildfire liability.", "method": METHOD, "results": [res("P5"), res("P6"), res("P7", "ground-truth EIA-930 hydro anomaly as signal (upper bound)"), res("U1_dz3"), res("U2_z"), res("U3_z"),
  {"metric": "WECC deseasonalised hydro vs gas+coal, lag 0 [EXPLORATORY replication of scout]", "value": round(float(E.r["E4_wecc_hydro_fossil"]), 3), "n": int(E.n["E4_wecc_hydro_fossil"]), "note": f"slope {E.slope['E4_wecc_hydro_fossil']:+.2f} MWh fossil per MWh hydro; p={E.maxstat_p['E4_wecc_hydro_fossil']:.3f}. Weaker than scout's -0.85/R2=0.64 (different BA list and sample)"},
  {"metric": "California 4-reservoir z vs CAISO hydro anomaly, lag 0 [EXPLORATORY]", "value": round(float(E.r["E4_z_CISO hydro"]), 3), "n": int(E.n["E4_z_CISO hydro"]), "note": f"uncorrected p={E.maxstat_p['E4_z_CISO hydro']:.3f}; vs CAISO gas r={E.r['E4_z_CISO gas']:+.2f} (p={E.maxstat_p['E4_z_CISO gas']:.2f})"}],
 "controls": "Placebos; DXY partial-out for NG=F.", "verdict": "rejected", "known_or_novel": "hydro-gas substitution is known (EIA Today-in-Energy drought notes); price-leg null is ours", "prior_art": ["https://www.eia.gov/todayinenergy/detail.php?id=51839"], "figures": [fig("fig4_family_overview.png")], "scripts": sc("signals.py", "run_tests.py", "exploratory.py"),
 "caveats": "EIA-930 by-source data starts 2018-07 (n~92 months; P7 n=58). Henry Hub is a national price; a SoCal/PG&E citygate basis would be the right target but no keyless series was found. The P5/P6 miss is a design error in the pre-registration (geography), reported as-is."})
F.append({"id": "F", "title": "Gas-flare radiative power (Libya, Basra) -> Brent, Brent-WTI, tanker equities", "one_liner": "Orbit cleanly sees outages (Libya 2020 blockade: flares -53%%) but 2-week flare changes have no relation to subsequent Brent returns (r=%+.3f, n=%d, p=%.2f); prices move on the news, satellites confirm magnitude later." % (R.r["F1"], R.n["F1"], R.maxstat_p["F1"]),
 "datasets": [DS["gibs"], DS["yf"]], "mechanism": "Associated-gas flaring scales with oil throughput; a flaring collapse = shut-in = supply loss.", "method": METHOD + " Weekly clear-sky index = mean of 3 brightest nights per Fri-Thu week over persistent flare cells; signal known before Friday close.",
 "results": [res(i) for i in ["F1", "F2", "F3", "F4", "F5"]] + [{"metric": "case studies: Libya outages (n=4, NOT statistics)", "value": json.dumps(CS["libya"]), "n": 4, "note": "flare drop -21% / -53% / -29% / -4%; Brent 4-week return after: +2.8 / -6.7 / +3.4 / -9.1 % -> no consistent sign"},
  {"metric": "F3 robustness: log(Libya/Algeria) ratio index -> tankers [EXPLORATORY]", "value": round(float(E.r["E9_TANKERS(FRO,DHT)-^GSPC"]), 3), "n": int(E.n["E9_TANKERS(FRO,DHT)-^GSPC"]), "note": "sign flips vs the pre-registered F3 (-0.116) -> F3's nominal p=0.019 is noise"}],
 "controls": "Algeria placebo flare index vs Brent: p=%.2f. Plotting exposed a sensor artefact (S-NPP safe-mode gap, Jul-Aug 2022) that appears as a simultaneous 'collapse' in Libya and the Algeria placebo." % PL[PL.placebo_signal == "algeria_flare"].maxstat_p.iloc[0],
 "verdict": "rejected", "known_or_novel": "flaring-as-production-proxy is known (Elvidge/Payne Institute VIIRS Nightfire; wardamage round 1); the 14-year keyless weekly lead-lag null is ours", "prior_art": ["https://www.mdpi.com/1996-1073/9/1/14", "https://payneinstitute.mines.edu/eog/"],
 "figures": [fig("fig3_libya_flares_brent.png"), fig("fig5_lag_profiles.png")], "scripts": sc("fetch_flares.py", "signals.py", "run_tests.py", "exploratory.py"),
 "caveats": "FRP is not barrels. The 2024-08 Libyan shut-in barely shows in flares (-4%). Archive (v1) vs NRT (v2.0) product versions differ; night filter derived from local solar time. Sovereign/FX legs untestable (pegged currencies, no keyless bond data). Basra's 2026 collapse is one regime shift (n=1)."})
F.append({"id": "R", "title": "Rhine low flow at Kaub -> BASF", "one_liner": "Correct sign, tiny and not significant: r=%+.3f, n=%d weeks, p=%.2f." % (R.r["R1"], R.n["R1"], R.maxstat_p["R1"]), "datasets": [DS["glofas"], DS["yf"]],
 "mechanism": "Kaub low water -> barges light-load -> Ludwigshafen logistics cost and curtailment (2018: ~EUR 250m).", "method": METHOD + " Stress = max(0, log(q10/Q)) with expanding 10th percentile.", "results": [res("R1")],
 "controls": "Danube (Budapest) and Loire (Saumur) placebo stress series vs BASF: p=%s." % ", ".join(f"{p:.2f}" for p in PL[PL.id == "R1"].maxstat_p), "verdict": "rejected", "known_or_novel": "macro effect of 2018 low water is known (Kiel Institute: -1.5% industrial production at peak); equity-return null is ours",
 "prior_art": ["https://www.kielinstitut.de/fileadmin/Dateiverwaltung/IfW-Publications/fis-import/d0c53966-8307-4bff-9cf9-13544afe7d80-KWP_2155_low_water_econ_activity.pdf", "https://www.wirtschaftsdienst.eu/inhalt/jahr/2019/heft/1/beitrag/niedrigwasser-bremst-produktion.html"],
 "figures": [fig("fig4_family_overview.png")], "scripts": sc("fetch_misc.py", "signals.py", "run_tests.py"), "caveats": "GloFAS is a model reanalysis (not a satellite observation), and Open-Meteo serves the consolidated series rather than the real-time vintage (mild look-ahead, which makes the null stronger). Stress is zero in ~90% of weeks: the test is driven by 2003, 2011, 2015, 2018, 2022."})
nord = [res("N1")] + ([res("P8", "SYS price is served by Energi Data Service for 2000-2010 only; r by lag 0..4 = " + R.r_by_lag["P8"]), {"metric": "NO2 area price 2011-2025 [EXPLORATORY]", "value": round(float(E.r["E10_NO2"]), 3), "n": int(E.n["E10_NO2"]), "note": "r by lag 0..4 = " + str(E.r_by_lag["E10_NO2"]) + ": coincident only"}] if "P8" in R.index else [{"metric": "P8 NVE filling -> Nord Pool SYS price", "value": None, "n": 0, "note": "NOT RUN: Energi Data Service returned HTTP 429 with multi-minute retry-after for every yearly request; recorded as an access blocker. fetch_nordpool.py resumes from cache."}])
F.append({"id": "N", "title": "Norwegian reservoir filling (NVE ground truth) -> Nord Pool price, Norsk Hydro", "one_liner": ("Weekly filling surprises move the Nord Pool system price in the same week (r=%+.2f, n=%d, 2000-2010; NO2 2011-2025 exploratory r=%+.2f) fading to %+.2f one week later (partly mechanical: weekly-average prices; NVE is published mid-following-week) and ~0 beyond; " % (R.r["P8"], R.n["P8"], E.r["E10_NO2"], json.loads(R.r_by_lag["P8"])[1]) if "P8" in R.index else "Nord Pool leg not run (rate-limited source); ") + "Norsk Hydro excess return: null (r=%+.3f, n=%d, p=%.2f)." % (R.r["N1"], R.n["N1"], R.maxstat_p["N1"]),
 "datasets": [DS["nve"], DS["eds"], DS["yf"]], "mechanism": "Hydro balance is the textbook driver of the Nordic system price; Hydro is both a hydropower seller and a smelter power buyer (sign ambiguous).", "method": METHOD + " NVE is ground truth, not satellite: GWW area is unusable in Norway in winter (ice/snow).", "results": nord,
 "controls": "SPGSCI/DXY partial-out for N1; split-sample replication of P8 on a different price series and decade (E10).", "verdict": "partial", "known_or_novel": "hydro-balance -> Nordic price is known", "prior_art": ["https://www.nve.no/energi/analyser-og-statistikk/magasinstatistikk/"], "figures": [fig("fig4_family_overview.png")], "scripts": sc("fetch_nordpool.py", "signals.py", "run_tests.py"), "caveats": "Verdict 'partial' = physical->power-price link supported (coincident), equity leg rejected. NVE is a ground-truth survey, not a satellite product; the same-week correlation partly reflects weather (inflow and demand) driving both. NVE publishes with ~3 days lag, so lag 0 is a nowcast, not a forecast. OSEBX.OL history on Yahoo starts 2013."})
json.dump(F, open(H / "findings.json", "w"), indent=1, ensure_ascii=False); print(len(F), "findings;", {f["id"]: f["verdict"] for f in F})
