import json, pandas as pd, numpy as np
from build_findings import R, DS, D
F = json.load(open(D+"findings_part2.json"))
fa = pd.read_csv(D+"foreign_activity_index.csv"); fa["ratio"] = fa.idx_war/fa.idx_same_window_2025; det = fa[fa.detectable]; ctl = pd.read_csv(D+"no2_controls_results.csv"); cal = json.load(open(D+"no2_calibration.json"))
grp = det.country.where(det.country.isin(["IRN", "IRQ"]), "GULF"); ck = ctl.groupby("kind").war_over_2025.median()
F.append(dict(id="no2_war_window_gulf_iran", title="NO2 over Iranian and Gulf power-plant sites fell sharply in the 28 Feb-8 Apr 2026 war window -- but so did NO2 over the cities, so it is not a power-plant signal", one_liner=f"Index vs the same weeks of 2025: Iranian plants x{det[grp == 'IRN'].ratio.median():.2f} (all {int((det[grp == 'IRN'].placebo_p_low < 0.05).sum())}/{int((grp == 'IRN').sum())} with placebo p<0.05), Gulf plants x{det[grp == 'GULF'].ratio.median():.2f}; Iranian cities x{ck['iran_city']:.2f}, Gulf cities x{ck['gulf_city']:.2f}, far-from-theatre cities x{ck['far_city']:.2f}.",
  datasets=[DS["s5p"], DS["gppd"], DS["era5"], DS["geonames"], DS["s2"]], mechanism="Strikes, fuel disruption, evacuation and industrial shutdown reduce combustion of all kinds; TROPOMI sees total NOx within ~10-50 km, not the plant alone.",
  method="41 GPPD sites >= 1 GW hand-checked on Sentinel-2 contact sheet; daily wind-rotated NO2 enhancement 2025-01-01..2026-09-10 from s3://meeo-s5p; index relative to pre-war mean with the US-learned temperature coefficient; war window vs same calendar window 2025, vs prior/following 60 days, and vs all 40-day placebo windows in the pre-war record; US-calibrated implied NOx band; 16 control sites (Iranian, Gulf, and far-from-theatre city centres) run through the identical pipeline. Contamination flags: stronger NO2 peak within 45 km, city >300k within 30 km, other GPPD thermal capacity within 30 km, manual notes (refineries, smelters).",
  results=[R("sites detectable / flagged contaminated / clean+detectable", int(fa.detectable.sum()), len(fa), f"{int(fa.contaminated.sum())} contaminated; only {int((fa.detectable & ~fa.contaminated).sum())} clean (Shirvan, Kazeroon, Shoaiba, Riyadh PP11-12, Shuqaiq)"),
           R("Iran plants: median war-window index (1 = pre-war mean)", det[grp == "IRN"].idx_war.median(), int((grp == "IRN").sum()), f"same window 2025 {det[grp == 'IRN'].idx_same_window_2025.median():.2f}, prior 60 d {det[grp == 'IRN'].idx_pre60.median():.2f}, following 60 d {det[grp == 'IRN'].idx_post60.median():.2f}"),
           R("Gulf plants: median war-window index", det[grp == "GULF"].idx_war.median(), int((grp == "GULF").sum()), f"same window 2025 {det[grp == 'GULF'].idx_same_window_2025.median():.2f}, following 60 d {det[grp == 'GULF'].idx_post60.median():.2f}; {int((det[grp == 'GULF'].placebo_p_low < 0.05).sum())} plants with placebo p<0.05"),
           R("Iraq plants: median war-window index", det[grp == "IRQ"].idx_war.median(), int((grp == "IRQ").sum())),
           R("US-calibrated implied NOx for the median Iranian plant (relative to normal)", det[grp == "IRN"].implied_rel_nox.median(), None, f"80% band {det[grp == 'IRN'].implied_lo80.median():.2f}-{det[grp == 'IRN'].implied_hi80.median():.2f}; single-plant no-change band for the index is {cal['nochange_index_q10']:.2f}-{cal['nochange_index_q90']:.2f}"),
           R("CONTROL Iranian city centres war/2025 ratio (median of 7)", ck["iran_city"], 7, "Tehran 0.54, Tabriz 0.37, Qom 0.47, Ahvaz 0.50, Mashhad 1.00"), R("CONTROL Gulf city centres ratio (median of 4)", ck["gulf_city"], 4),
           R("CONTROL far-from-theatre cities ratio (Jeddah, Medina, Muscat, Ashgabat)", ck["far_city"], 4, "no dip -> not a retrieval or seasonal artefact"),
           R("June 2025 12-day war: median index, Iranian plants", det[grp == "IRN"].idx_jun2025_war.median(), int(det[grp == "IRN"].idx_jun2025_war.notna().sum()), "no dip detectable in a 12-day window")] +
          [R(f"{r['name']} ({r.country}) war index", r.idx_war, r.n_war, f"2025 same window {r.idx_same_window_2025:.2f}; placebo p {r.placebo_p_low:.2f}; {'CONTAMINATED: ' + str(r.flags)[:90] if r.contaminated else 'clean'}") for _, r in det.sort_values("idx_war").head(12).iterrows()],
  controls="Same-calendar-window 2025; placebo windows; city-centre and far-site controls through the identical pipeline; US no-change band.", verdict="partial",
  known_or_novel="novel for this event as far as we found (we did not find published TROPOMI analyses of the 2026 war); the COVID-lockdown NO2 literature is the obvious analogue", prior_art=["https://www.iranintl.com/en/202606115946", "https://pmc.ncbi.nlm.nih.gov/articles/PMC6853767/"],
  figures=["figs/foreign_no2_index.png", "figs/contact_foreign.png"], scripts=["s5p_region.py", "no2_index.py", "no2_foreign.py", "no2_controls.py", "s2_contact.py", "weather_fetch.py"],
  caveats="WHAT WE CAN SAY: a theatre-wide 30-50% drop in NO2 near large combustion sites during the war window, recovering by May-June in the Gulf and only partly in Iran. WHAT WE CANNOT SAY: that any individual power plant reduced output -- 35 of 39 detectable sites share their TROPOMI footprint with a city, refinery, smelter or another plant, and city centres fell as much as plant sites. Only 8-25 valid days per site in the window. Placebo distribution has ~40 overlapping windows from a single pre-war year. GPPD coordinates are off by 1-3 km at several sites (Qurayyah, Faras) and unverifiable at 3 (Al-Anbar, Al-Shemal, Jazan)."))
ip = pd.read_csv(D+"s2_iran_plume_index.csv"); vis = ip[ip.plume_rate_cold_lt12C > 0.5]
F.append(dict(id="s2_iran_winter_plumes", title="Sentinel-2 stack plumes at Iranian/Iraqi plants: the visible ones kept running through the 2026 war window", one_liner=f"{len(vis)} of 17 plants show plumes in >50% of cold-weather scenes (Shahid Rajaee {ip.set_index('plant').loc['IRN_RAJAEE', 'plume_rate_cold_lt12C']:.2f}, Montazeri, Shazand, Ramin, Mussaib, Al-Anbar); in the war window their plume rate was {vis.rate_war.median():.2f} vs {vis.rate_ref2025.median():.2f} a year earlier -- no detectable shutdown, n=5-9 scenes each.",
  datasets=[DS["s2"], DS["osm"], DS["era5"], DS["gppd"]], mechanism="Iranian plateau plants use dry (Heller) cooling towers, so the visible plume is flue gas from the stacks condensing in cold air (reportedly with heavy-fuel-oil firing in winter); presence of a plume means the unit is firing.",
  method="Same label-free plume detector anchored on OSM chimneys/towers, 12 Iranian + 5 Iraqi plants, 2024-10..2026-09 (3,337 chips); plume present = attached bright area > 0.01 km2; war window vs same window 2025 with ERA5 temperature; Mann-Whitney on plume area.",
  results=[R(f"{r.plant}: plume rate war window", r.rate_war, r.n_war, f"same window 2025 {r.rate_ref2025:.2f} (n={int(r.n_ref2025)}); T war {r.T_war:.0f}C vs {r.T_ref2025:.0f}C; MWU p={r.p_mannwhitney_area_war_vs_2025:.2f}" if pd.notna(r.p_mannwhitney_area_war_vs_2025) else f"same window 2025 {r.rate_ref2025:.2f} (n={int(r.n_ref2025)})") for _, r in vis.iterrows()] +
          [R("plants with essentially no visible plume (gas CCGT / hot sites)", int((ip.plume_rate_all < 0.1).sum()), len(ip), "Kerman, Fars, Damavand, Kazeroon, Aliabad: method blind")],
  controls="Same calendar window one year earlier with temperature recorded (war window was 2-5 C colder, which by itself favours plume visibility).", verdict="partial", known_or_novel="novel application; no ground truth",
  prior_art=["https://www.mdpi.com/2072-4292/16/7/1290"], figures=["figs/iran_s2_plume_index.png", "s2_foreign_montage.png"], scripts=["s2_extract2.py", "osm_towers.py", "s2_features.py", "s2_iran.py"],
  caveats="No labels anywhere: this is on/off evidence only, for ~6 plants, with 5-9 clear scenes each in the window. Montazeri shows a constant ~0.04 km2 'plume' in summer that is a ground artefact. The US-trained load model was NOT applied here because stack plumes from dry-cooled oil/gas units are outside its training distribution."))
so = pd.read_csv(D+"so2_foreign_results.csv"); from sklearn.metrics import roc_auc_score
F.append(dict(id="so2_fuel_discrimination", title="TROPOMI SO2 separates oil-burning from gas-burning plants in the Gulf/Iran/Iraq", one_liner=f"SO2 plume t-statistic: median {fa[fa.fuel == 'Oil'].so2_t.median():.1f} at GPPD 'Oil' plants vs {fa[fa.fuel == 'Gas'].so2_t.median():.1f} at 'Gas' plants; AUC {roc_auc_score(fa.fuel == 'Oil', fa.so2_t):.2f} (14 vs 27). Shahid Rajaee, listed as gas, shows a strong SO2 plume.",
  datasets=[DS["s5p"], DS["gppd"], DS["era5"]], mechanism="Heavy fuel oil / crude burned without FGD emits percent-level sulphur; pipeline gas emits almost none.",
  method="Same wind-rotated box estimator on the L2 SO2 total vertical column COGs (qa>=0.5), 2025-01..2026-09, ~530 valid days per site; t = mean/SE of daily enhancement; label = GPPD primary_fuel.",
  results=[R("AUC, SO2 t-stat, Oil vs Gas", roc_auc_score(fa.fuel == "Oil", fa.so2_t), len(fa)), R("AUC, NO2 t-stat, Oil vs Gas (control)", roc_auc_score(fa.fuel == "Oil", fa.t_stat), len(fa), "NO2 does not discriminate fuel nearly as well"),
           R("plants with SO2 t > 5", int((fa.so2_t > 5).sum()), len(fa)), R("Shahid Rajaee (GPPD: Gas) SO2 t-stat", fa.set_index("plant").loc["IRN_RAJAEE", "so2_t"], None, "consistent with liquid-fuel firing; also visible dark stack plumes in Sentinel-2"),
           R("Iranian oil/dual-fuel plants: winter (DJF) vs summer (JJA) SO2 enhancement, median ratio", (so[(so.country == "IRN") & (so.so2_t > 5)].so2_winter/so[(so.country == "IRN") & (so.so2_t > 5)].so2_summer).median(), int(((so.country == "IRN") & (so.so2_t > 5)).sum()), "CONFOUNDED: SO2 lifetime is also ~2x longer in winter"),
           R("SO2-detectable plants: war window / same window 2025", (so[so.so2_t > 5].so2_war/so[so.so2_t > 5].so2_same_window_2025).median(), int((so.so2_t > 5).sum()))],
  controls="NO2 t-stat as a control discriminator; gas plants as the negative class.", verdict="supported", known_or_novel="known that TROPOMI sees Gulf oil-fired plants (Fioletov SO2 catalogue); fuel-label AUC on a plant list is a small addition",
  prior_art=["https://so2.gsfc.nasa.gov/measures.html"], figures=[], scripts=["no2_index.py", "so2_analysis.py", "no2_foreign.py"], caveats="GPPD fuel labels are 2021-vintage and dual-fuel plants are common; refineries next to several 'oil' plants (Rabigh, Montazeri, Shazand) also emit SO2; no US test possible because US plants are scrubbed."))
au = pd.read_csv(D+"no2_au_results.csv")
F.append(dict(id="no2_index_australia", title="The 30-day NO2 index also tracks Australian plant output (AEMO), with the same modest skill as in the US", one_liner=f"Median r between the 30-day index and 30-day mean MW = {au.r_30d_nonoverlap.median():.2f} across 10 plants (range {au.r_30d_nonoverlap.min():.2f} to {au.r_30d_nonoverlap.max():.2f}); daily r median {au.r_daily_overpass.median():.2f}.",
  datasets=[DS["s5p"], DS["aemo"], DS["era5"]], mechanism="Australian coal units have no SCR, so NOx should follow generation more closely than in the US.", method="Same estimator and US-learned temperature coefficient, Australia grid 2024-07..2026-06; label = AEMO plant MW (daily mean; 11-13h AEST for daily test); one value per 30-day block.",
  results=[R(f"{r.plant} 30-day r", r.r_30d_nonoverlap, r.n_nonoverlap, f"daily r {r.r_daily_overpass:.2f} (n={r.n_days}); CV of 30-day MW {r.cv_mw_30d:.2f}") for _, r in au.iterrows()], controls="None beyond the US seasonality placebo; Australian load and NO2 lifetime both peak in winter, so part of r may be seasonal.",
  verdict="partial", known_or_novel="novel as a check; small n", prior_art=[], figures=[], scripts=["no2_au.py"], caveats="12-24 independent windows per plant (95% CI on r roughly +-0.4); Tarong again fails (r=-0.09); Loy Yang and Yallourn share a TROPOMI footprint; Eraring sits next to Newcastle/Vales Point."))
oi = pd.read_csv(D+"orphans_idn.csv"); om = pd.read_csv(D+"orphans_me.csv")
F.append(dict(id="orphan_nox_sources", title="Persistent NO2 hot spots with no (or token) entry in the WRI plant database: Indonesian nickel parks and Iranian industrial zones", one_liner=f"Sulawesi/Halmahera box: {len(oi)} hot spots, {int(oi.orphan.sum())} with zero GPPD capacity within 25 km; Morowali is the brightest at {oi.enh_umol_m2.max():.0f} umol/m2 -- brighter than any US coal plant in our sample (max ~10) -- against 280 MW listed.",
  datasets=[DS["s5p"], DS["gppd"], DS["geonames"], DS["s2"]], mechanism="Captive coal plants and smelters built after ~2018 are missing from the 2021-frozen GPPD but emit NOx continuously.",
  method="12-month (IDN) / 20-month (Middle East) mean NO2 on 0.035 deg grid minus 120-km median background; local maxima with enhancement > 6 umol/m2 and t > 5; matched to GPPD thermal plants within 25 km and GeoNames cities > 100k within 30 km; top candidates eyeballed on Sentinel-2.",
  results=[R(f"IDN hot spot {r.lat:.2f},{r.lon:.2f}", r.enh_umol_m2, r.ndays, f"GPPD MW within 25 km: {r.gppd_mw_within_25km:.0f}; city: {r.city_within_30km if isinstance(r.city_within_30km, str) else 'none'}") for _, r in oi.head(7).iterrows()] +
          [R("IDN sites where Sentinel-2 shows a large industrial complex at the hot spot", 4, 5, "Morowali (-2.83,122.15), Weda Bay (0.46,127.99), -2.02/121.41 (N. Morowali), Kendari-Morosi (-3.88,122.43); -2.27/121.73 unclear"),
           R("Middle East orphan hot spots (no GPPD plant, no city>100k)", int(om.orphan.sum()), len(om), "top: 27.73N 52.18E (Asaluyeh/South Pars coast, 124 umol/m2), 29.13N 55.37E (Sirjan mining/steel complex), 32.35N 53.76E; first three show industrial complexes in Sentinel-2, next three unverified")],
  controls="City filter; GPPD match; visual check.", verdict="partial", known_or_novel="known to specialists (CREA/GEM track Indonesian captive coal); the automatic keyless screen is ours", prior_art=["https://globalenergymonitor.org/projects/global-coal-plant-tracker/"],
  figures=["orphans_idn.png", "figs/orphans_idn_s2.png", "orphans_me.png", "figs/orphans_me_s2.png"], scripts=["no2_orphans.py", "s2_contact.py"], caveats="Site identities (IMIP, IWIP, GNI, VDNI, South Pars, Gol Gohar) are the author's belief from location, NOT verified against a dataset. 122 Middle-East 'orphans' are mostly oil/gas fields, cement and towns under 100k -- a long speculative list; only the top 3 were looked at. Tropical cloud leaves 50-150 valid days/yr."))
F.append(dict(id="label_free_source_finder", title="Finding the plume source without any map (recurring-bright-anomaly hot spot) does not work", one_liner="The unsupervised source locator locked onto ash dams, mine faces and coal piles at 6 of 8 Australian plants; OSM cooling-tower/chimney coordinates were required.",
  datasets=[DS["s2"], DS["osm"]], mechanism="Anything whose brightness changes often looks like a plume source to a frequency map.", method="Frequency map of bright whiteness anomalies across clear scenes; visual audit on 8 Australian plants (figs/debug_au.png).",
  results=[R("plants where the auto-located source was the cooling towers", 2, 8, "Yallourn, partly Loy Yang"), R("plants (of 73) with OSM cooling towers or chimneys mapped", 72, 73, "only Al-Anbar (Iraq) had neither")], controls="Visual audit.", verdict="rejected", known_or_novel="novel negative result",
  prior_art=[], figures=["figs/debug_au.png"], scripts=["s2_features.py", "s2_debug_fig.py"], caveats="The fallback is still used for mechanical-draft towers (not mapped in OSM) restricted to 800 m around mapped chimneys, which is probably why mechanical-draft results are poor."))
F.append(dict(id="keyless_data_access", title="Everything needed is reachable anonymously, but two 'obvious' hosts are not", one_liner="CEMS (PUDL S3), TROPOMI NO2/SO2 COGs (meeo-s5p), Sentinel-2 COGs (Earth Search), AEMO 5-min SCADA, ERA5 via Open-Meteo, OSM via Overpass mirrors, GPPD and GeoNames all worked without accounts; Copernicus Data Space assets, usgs-landsat, Earth Engine and Earthdata do not.",
  datasets=list(DS.values()), mechanism="n/a", method="Every source was exercised by the scripts in this directory from a laptop.",
  results=[R("TROPOMI CONUS daily composites, 36 months", 1096, None, "~0.5 GB streamed and ~70 s per month when uncontended; 1.1 GB stored as float16"), R("Sentinel-2 chips extracted (TCI+SCL, 20 m, 4 km)", 9276 + 2356 + 3337, None, "~1 chip/s per plant thread; 10 m single bands were 10x slower because COG blocks are 1024 px"),
           R("AEMO months downloaded", 37, None, "~30 MB each, file naming changed mid-2024"), R("CEMS remote query, 46-58 plants x 3.5 yr", 1000, None, "seconds; whole-US 2024 aggregate ~10 min")],
  controls="n/a", verdict="supported", known_or_novel="known", prior_art=[], figures=[], scripts=["s5p_region.py", "s2_extract2.py", "aemo_fetch.py", "cems_fetch2.py", "weather_fetch.py", "osm_towers.py"],
  caveats="Open-Meteo hourly rate limit was hit once (resumable fetcher added); overpass-api.de returned HTTP 406, two mirrors worked; Taipower and India NPP were NOT tested this round; ~60 GB was streamed in total."))
usdet = pd.read_csv(D+"no2_detectability_us.csv"); nchips = sum(len(pd.read_csv(D+f"s2_features_{k}.csv")) for k in ("us", "au", "ir"))
for f in F:
    if f["id"] == "keyless_data_access":
        f["caveats"] = f["caveats"].replace("~60 GB was streamed in total", "roughly 50-70 GB was streamed in total (estimate, not metered)")
        for r in f["results"]:
            if r["metric"].startswith("Sentinel-2 chips"): r["value"] = nchips
    if f["id"] == "so2_fuel_discrimination": f["prior_art"] = []; f["known_or_novel"] += " (catalogue reference not re-checked this round)"
    if f["id"] == "orphan_nox_sources": f["one_liner"] = f["one_liner"].replace("brighter than any US coal plant in our sample (max ~10)", "several times the enhancement of any US plant in our sample (box-mean max %.0f umol/m2; metrics not identical)" % usdet["mean"].max())
json.dump(F, open(D+"findings.json", "w"), indent=1); print(len(F), "findings ->", D+"findings.json"); print([f["id"]+":"+f["verdict"] for f in F])
