import json, pandas as pd, numpy as np, os
from build_findings import R, DS, D
F = json.load(open(D+"findings_part1.json"))
c = pd.read_csv(D+"no2_calibration_results.csv").set_index("metric"); det = pd.read_csv(D+"no2_detectability_us.csv"); lag = pd.read_csv(D+"no2_placebo_lag1y.csv"); cz = pd.read_csv(D+"no2_calibration_by_index.csv"); cal = json.load(open(D+"no2_calibration.json"))
def cm(prefix): x = c[c.index.str.startswith(prefix)].iloc[0]; return x.value, x.n, x.note if isinstance(x.note, str) else ""
F.append(dict(id="no2_daily_per_plant", title="Daily TROPOMI NO2 over a single US power plant barely tracks its reported NOx", one_liner=f"Median per-plant daily r = {cm('daily per-plant pearson r vs CEMS NOx, median [wind-rotated enh, 2-9 m/s]')[0]:.2f} over 58 isolated plants and 3 years; wind rotation and flux scaling do not help; 16 of 58 plants are below TROPOMI's detection limit.",
  datasets=[DS["s5p"], DS["cems"], DS["era5"]], mechanism="NOx from the stack forms an NO2 plume a few TROPOMI pixels long; column enhancement downwind minus upwind should scale with emission rate.",
  method="58 isolated CEMS plants (38 coal, 20 'gas' by EIA-860 dominant capacity; neighbours within 60 km emit <25-35% of own NOx). Daily qa>=0.75 composites on a 0.035 deg CONUS grid, 2023-07..2026-06 (1,096 days). Enhancement = mean of 55x24 km downwind box minus upwind median, ERA5 100 m wind at ~13:30 local; label = CEMS NOx over the 3 h before overpass. Ablations: no rotation, enh*u^a (a=0,0.5,1), 2-9 m/s filter.",
  results=[R(k.split("[")[1][:-1], c.loc[k, "value"], c.loc[k, "n"], c.loc[k, "note"]) for k in c.index if k.startswith("daily per-plant pearson r vs CEMS NOx")] +
          [R("pooled daily r vs NOx", *cm("daily pooled pearson flux vs NOx")[:2]), R("pooled daily r vs MW", *cm("daily pooled pearson flux vs MW")[:2], "NOx is decoupled from generation by SCR/low-NOx burners"),
           R("plants passing label-free detectability screen", int(det.detectable.sum()), len(det), f"median CEMS NOx passing {det[det.detectable].nox_lbs_h.median():.0f} lbs/h vs failing {det[~det.detectable].nox_lbs_h.median():.0f} lbs/h (literature detection limit ~240-870 lbs/h)"),
           R("daily r, coal vs gas-dominant plants", cm("daily per-plant r, fuel=coal")[0], 38, f"gas {cm('daily per-plant r, fuel=gas')[0]:.2f} (n=20)")],
  controls="Same pipeline, same plants, three estimator variants; simple unrotated disc-minus-annulus does as well as the wind-rotated box.", verdict="rejected",
  known_or_novel="known (literature reports 40-100% single-overpass error); our null on wind rotation is specific to this crude box estimator", prior_art=["https://acp.copernicus.org/articles/26/4405/2026/", "https://pmc.ncbi.nlm.nih.gov/articles/PMC6853767/", "https://essd.copernicus.org/articles/15/3051/2023/"],
  figures=["figs/no2_us_calibration.png"], scripts=["s5p_region.py", "no2_index.py", "cems_fetch2.py", "no2_calibrate.py"], caveats="Daily composite mixes orbits; overpass time approximated as 13:30 local solar; no AMF/plume-height correction; 0.035 deg regridded product, not native pixels."))
F.append(dict(id="no2_30day_calibrated_index", title="A 30-day TROPOMI NO2 index per plant, with bands calibrated on held-out US plants", one_liner=f"Leave-plants-out: 30-day index vs 30-day CEMS NOx r = {cm('30-day held-out: pooled pearson, temperature-corrected index')[0]:.2f} (n={int(cm('30-day held-out: pooled pearson, temperature-corrected index')[1])} windows); a real 30-day outage is caught {100*cm('outage detection rate at 5% false alarms, 30-day, temperature-corrected')[0]:.0f}% of the time at 5% false alarms (AUC {cm('outage detection AUC, 30-day, temperature-corrected held-out index')[0]:.2f}).",
  datasets=[DS["s5p"], DS["cems"], DS["era5"]], mechanism="Averaging ~10-20 valid overpasses beats down retrieval/meteorological noise; NO2 lifetime varies with temperature, so a temperature coefficient learned on training plants is applied to test plants.",
  method="42 plants passing the label-free detectability screen. Index = 30-day rolling mean of wind-filtered enhancement / plant long-run mean, divided by exp(b*(T-15)), b learned on training plants (GroupKFold 6). Linear calibration to relative CEMS NOx (30-day all-hours mean / plant mean) with 10-90% residual band from training folds; evaluated on non-overlapping windows of held-out plants. Outage = 30-day NOx <30% of plant normal vs >70%.",
  results=[R("held-out pooled r, raw relative index", *cm("30-day held-out: pooled pearson, raw relative index")[:2]), R("held-out pooled r, temperature-corrected", *cm("30-day held-out: pooled pearson, temperature-corrected index")[:2]),
           R("median within-plant r, 14 / 30 / 60-day", cm("30-day index: within-plant pearson median")[0], 42, f"14-day {cm('14-day index: within-plant pearson median')[0]:.2f}; 60-day {cm('60-day index: within-plant pearson median')[0]:.2f}"),
           R("80% interval coverage on held-out plants", *cm("30-day held-out: 80% prediction-interval coverage")[:2], cm("30-day held-out: 80% prediction-interval coverage")[2]),
           R("RMSE of relative NOx", *cm("30-day held-out: RMSE of relative NOx")[:2], cm("30-day held-out: RMSE of relative NOx")[2]),
           R("index value when NOx truly unchanged (10-90%)", cal["nochange_index_q10"], None, f"to {cal['nochange_index_q90']:.2f}: a single plant must fall below ~{cal['nochange_index_q10']:.2f} of normal before a change is distinguishable"),
           R("temperature coefficient of NO2-per-NOx", cal["temp_coef_per_degC"], None, "per deg C; ~-2%/C, i.e. 2x more NO2 per unit NOx at 0 C than at 30 C")] +
          [R(f"calibration: index in {r.flux_rel_corr} -> relative NOx median", r["50%"], r["count"], f"10-90%: {r['10%']:.2f}-{r['90%']:.2f}") for _, r in cz.iterrows()] +
          [R("outage detection AUC 14/30/60-day (uncorrected)", cm("outage detection AUC, 30-day window")[0], cm("outage detection AUC, 30-day window")[1], f"14-day {cm('outage detection AUC, 14-day window')[0]:.2f}, 60-day {cm('outage detection AUC, 60-day window')[0]:.2f}"),
           R("outage detection rate at 5% FA, 30-day, temp-corrected", *cm("outage detection rate at 5% false alarms, 30-day, temperature-corrected")[:2], cm("outage detection rate at 5% false alarms, 30-day, temperature-corrected")[2])],
  controls=f"Seasonality placebo: the index correlates with THIS year's NOx (median r {lag.r_actual.median():.2f}) much better than with the same dates one year later/earlier (median r {lag.r_lag1y.median():.2f}); actual > lagged at {int((lag.r_actual > lag.r_lag1y).sum())}/{len(lag)} plants.",
  verdict="supported", known_or_novel="method known (Beirle, Goldberg); the leave-plants-out 'how much does an X move imply, with coverage-checked band, and outage detection power' product is our addition",
  prior_art=["https://pmc.ncbi.nlm.nih.gov/articles/PMC6853767/", "https://pubs.acs.org/doi/abs/10.1021/acs.est.9b04488", "https://acp.copernicus.org/articles/26/4405/2026/"], figures=["figs/no2_us_calibration.png"], scripts=["no2_calibrate.py", "no2_placebo.py", "no2_fig.py"],
  caveats="Bands are wide: index at 50% of normal is consistent with NOx anywhere from ~25% to ~110% of normal. Index does not reach zero in real outages (median 0.48) because of background/neighbour NO2. Detectability thresholds (mean enh >= 2 umol/m2, t >= 8) were set after seeing that undetectable plants destroy the pooled relation. Tracks NOx, not MW (r vs MW ~0.3)."))
rg = pd.read_csv(D+"no2_regional_results.csv"); fo = rg[rg.target == "fossil"]; co = rg[rg.target == "coal"]
F.append(dict(id="no2_regional_aggregation", title="Summing NO2 enhancements over a balancing authority does not generally rescue the weak daily signal", one_liner=f"Median r vs EIA-930 fossil generation across 13 BAs: daily {fo.r_daily_tempcorr.median():.2f}, weekly {fo.r_weekly_tempcorr.median():.2f}, monthly {fo.r_monthly_tempcorr.median():.2f} (deseasonalised {fo.r_monthly_deseasonalised.median():.2f}); it works only in rural coal-heavy regions (SWPP {fo.set_index('ba').loc['SWPP', 'r_monthly_tempcorr']:.2f}, WACM {fo.set_index('ba').loc['WACM', 'r_monthly_tempcorr']:.2f}) and fails in urban ones (PJM {fo.set_index('ba').loc['PJM', 'r_monthly_tempcorr']:.2f}, NYIS {fo.set_index('ba').loc['NYIS', 'r_monthly_tempcorr']:.2f}).",
  datasets=[DS["s5p"], DS["eia930"], DS["cems"], DS["era5"]], mechanism="Independent per-plant noise should average down across many plants in a region; regional fossil generation is published hourly by EIA-930.",
  method="All CEMS plants with 2024 NOx >= 100 lbs/h (229 plants in 13 BAs with >= 4 plants). Per plant-day: mean NO2 within 15 km minus 50-100 km annulus median; BA index = mean over plants with valid data (>= 50% of plants), temperature-corrected with the plant-level coefficient; compared with EIA-930 coal+gas+oil and coal-only generation at daily/weekly/monthly means; control: remove month-of-year climatology from both series.",
  results=[R(f"{r.ba} ({r.n_plants} plants) monthly r vs fossil gen, temp-corrected", r.r_monthly_tempcorr, r.n_monthly, f"daily {r.r_daily_tempcorr:.2f} (n={r.n_daily}), weekly {r.r_weekly_tempcorr:.2f}; raw monthly {r.r_monthly:.2f}; deseasonalised {r.r_monthly_deseasonalised:.2f}") for _, r in fo.iterrows()] +
          [R("median across BAs, coal-only target, monthly", co.r_monthly_tempcorr.median(), len(co), f"daily {co.r_daily_tempcorr.median():.2f}, weekly {co.r_weekly_tempcorr.median():.2f}, deseasonalised {co.r_monthly_deseasonalised.median():.2f}")],
  controls="Deseasonalised monthly correlation; coal-only vs all-fossil target; raw vs temperature-corrected (without the correction the monthly r is ~0 because NO2 lifetime seasonality opposes summer load peaks).", verdict="partial",
  known_or_novel="novel as a test against EIA-930 as far as we found; the conclusion (urban NOx swamps power-sector NOx) is unsurprising", prior_art=["https://essd.copernicus.org/articles/15/3051/2023/"], figures=[], scripts=["no2_regional.py"],
  caveats="No wind rotation at regional scale; traffic/industry NOx is not separated; n=29-36 months per BA so monthly r has CI of roughly +-0.3; BA footprints overlap geographically."))
json.dump(F, open(D+"findings_part2.json", "w"), indent=1); print(len(F))
