"""Assemble findings.json from result CSVs (numbers are read, not typed)."""
import json, pandas as pd, numpy as np, os
D = "/Users/tomalmog/projects/kingdom/explore/powerplants/"
def R(metric, value, n=None, note=""): return dict(metric=metric, value=(None if value is None or (isinstance(value, float) and np.isnan(value)) else (round(float(value), 3) if not isinstance(value, str) else value)), n=(None if n is None else int(n)), note=note)
DS = dict(
 cems=dict(name="EPA CEMS hourly (PUDL core_epacems__hourly_emissions)", url="s3://pudl.catalyst.coop/nightly/core_epacems__hourly_emissions.parquet", access="anonymous S3/HTTPS, duckdb predicate pushdown; data through 2026-06-30"),
 eia860=dict(name="EIA-860 cooling equipment / plants (PUDL)", url="s3://pudl.catalyst.coop/nightly/_core_eia860__cooling_equipment.parquet", access="anonymous"),
 eia930=dict(name="EIA-930 hourly net generation by energy source (PUDL)", url="s3://pudl.catalyst.coop/nightly/core_eia930__hourly_net_generation_by_energy_source.parquet", access="anonymous"),
 s2=dict(name="Sentinel-2 L2A COGs (TCI + SCL)", url="https://earth-search.aws.element84.com/v1 -> s3://sentinel-cogs", access="anonymous STAC + HTTPS range reads"),
 s5p=dict(name="Sentinel-5P TROPOMI NO2/SO2 L2 as COGs (MEEO)", url="s3://meeo-s5p/COGT/OFFL/", access="anonymous S3, windowed COG reads"),
 aemo=dict(name="AEMO NEMWEB MMSDM DISPATCH_UNIT_SCADA (5-min per-unit MW)", url="https://nemweb.com.au/Data_Archive/Wholesale_Electricity/MMSDM/", access="anonymous HTTPS zip, ~30 MB/month"),
 era5=dict(name="ERA5 hourly weather via Open-Meteo archive API", url="https://archive-api.open-meteo.com/v1/archive", access="keyless; hourly rate limit hit once (HTTP 429)"),
 osm=dict(name="OpenStreetMap cooling towers / chimneys via Overpass mirrors", url="https://overpass.private.coffee/api/interpreter", access="keyless; overpass-api.de returned 406, mirrors worked"),
 gppd=dict(name="WRI Global Power Plant Database v1.3", url="https://github.com/wri/global-power-plant-database", access="keyless CSV; frozen 2021"),
 geonames=dict(name="GeoNames cities15000", url="https://download.geonames.org/export/dump/cities15000.zip", access="keyless"))
m2 = pd.read_csv(D+"s2_model_results_v2.csv"); m1 = pd.read_csv(D+"s2_model_results.csv"); cond = pd.read_csv(D+"s2_us_condition_splits_v2.csv"); boot = pd.read_csv(D+"s2_weather_gain_bootstrap.csv"); aup = pd.read_csv(D+"s2_au_per_plant_v2.csv"); lohi = pd.read_csv(D+"s2_au_low_vs_high.csv")
def g(df, subset, model, col): x = df[(df.subset == subset) & (df.model == model)]; return x[col].iloc[0], x.n.iloc[0]
US, ND, AUT, AUC_ = "US towers+FGD (natural+mech draft)", "US natural-draft only", "AU zero-shot: tower plants", "AU zero-shot: no-tower controls"
F = []
v, n = g(m2, US, "mono_gbt_img+wx", "auc_onoff"); noff = int(m2[(m2.subset == US)].n_off.iloc[0])
F.append(dict(id="s2_plume_us_onoff", title="Sentinel-2 steam plumes reveal whether a US power plant is running (leave-whole-plants-out)", one_liner=f"On plants the model never saw, a label-free plume detector separates on/off with AUC {v:.2f} ({noff} off-scenes, 41 plants) and ranks load with Spearman {g(m2, US, 'mono_gbt_img+wx', 'spearman_cf')[0]:.2f}.",
  datasets=[DS["s2"], DS["cems"], DS["eia860"], DS["osm"], DS["era5"]], mechanism="Wet cooling towers and wet-FGD stacks emit water vapour roughly in proportion to heat rejected; it condenses into a visible white plume whose size depends on load and on ambient temperature/humidity.",
  method="46 US plants chosen from EIA-860 cooling data (26 natural-draft, 15 mechanical-draft, 5 once-through), 3 years of Sentinel-2 (9,276 chips at 20 m, TCI+SCL). Plume = bright whiteness anomaly (vs rolling 30th-percentile clear reference) in connected components attached to OSM cooling-tower/chimney locations; cloud guards: SCL cloud fraction away from source <10%, bright-away <3%, snow <20%, reject >0.8 km2 plumes touching chip border; shadow-displacement feature. Monotone gradient-boosted model on 7 image + 5 weather features, GroupKFold by plant (6 folds). Label = CEMS gross load in the overpass hour / 99.5th pct load.",
  results=[R("on/off AUC, all tower+FGD plants, image+weather model", v, n, f"{noff} off scenes; raw plume area/GW AUC {g(m2, US, 'raw_area_per_GW', 'auc_onoff')[0]:.3f}; on/off classifier AUC {g(m2, US, 'clf_onoff_img+wx', 'auc_onoff')[0]:.3f}"),
           R("on/off AUC, natural-draft plants only", *g(m2, ND, "mono_gbt_img+wx", "auc_onoff"), f"{int(m2[m2.subset == ND].n_off.iloc[0])} off scenes"),
           R("average precision for the OFF class (natural-draft)", *g(m2, ND, "mono_gbt_img+wx", "ap_off"), "off base rate ~25%"),
           R("Spearman(model, capacity factor), all / natural-draft", g(m2, US, "mono_gbt_img+wx", "spearman_cf")[0], n, f"natural-draft {g(m2, ND, 'mono_gbt_img+wx', 'spearman_cf')[0]:.3f}; on-scenes only {g(m2, US, 'mono_gbt_img+wx', 'spearman_cf_on_only')[0]:.3f}"),
           R("load-tercile accuracy", g(m2, US, "mono_gbt_img+wx", "tercile_acc")[0], n, "chance 0.334"),
           R("median within-plant Spearman", g(m2, US, "mono_gbt_img+wx", "within_plant_spearman_median")[0], 41),
           R("usable scenes after cloud guards", len(pd.read_csv(D+"s2_us_cv_predictions_v2.csv")), 9276, "~28% of chips; ~21 usable scenes per plant-year"),
           R("mechanical-draft plants only: on/off AUC (first-pass model)", *g(m1, "US mech-draft only", "raw_plume_area", "auc_onoff"), "much weaker than natural draft")],
  controls=f"Weather-only model (no image): AUC {g(m1, US, 'weather_only(control)', 'auc_onoff')[0]:.2f}, Spearman {g(m1, US, 'weather_only(control)', 'spearman_cf')[0]:.2f} -> image carries the signal. Australian air-cooled plants (no towers) give Spearman ~0. Plant-bootstrap CIs in s2_us_bootstrap_ci.json.",
  verdict="supported", known_or_novel="known (Climate TRACE / WattTime, Carbon Tracker 2018, Hanna 2021); our label-free OSM-anchored detector + leave-plants-out numbers are an independent replication with public data only",
  prior_art=["https://www.mdpi.com/2072-4292/16/7/1290", "https://www.climatechange.ai/papers/neurips2020/11", "https://github.com/HSG-AIML/RemoteSensingCO2Estimation", "https://carbontracker.org/reports/nowhere-to-hide/"],
  figures=["figs/montage_gavin_us.png", "figs/s2_summary.png"], scripts=["select_plants.py", "cems_fetch2.py", "s2_extract2.py", "osm_towers.py", "weather_fetch.py", "s2_features.py", "s2_model.py", "s2_model2.py", "s2_montage.py", "s2_summary_fig.py"],
  caveats="Cloud leakage is reduced, not eliminated (clouds sitting on the towers still pass; the border rule also removes some genuine very large cold-weather plumes). Load level within the ON state is weak (Spearman ~0.38-0.43). Only ~4% of plants worldwide have the required structures. Capacity proxy uses CEMS 99.5th-percentile load (nameplate would be used abroad). Validity rule and model form were refined once after seeing first-pass results (both versions saved: s2_model_results.csv, s2_model_results_v2_before_borderrule.csv)."))
t = cond[cond.split == "Tbin"].copy(); t["bin"] = t.bin.str.extract(r"\(([-\d.]+),")[0].astype(float).map({-40.0: "cold", 5.0: "cool", 15.0: "mild", 25.0: "hot"}); t = t.set_index("bin"); b = boot.set_index("contrast")
B1, B2, B3 = "rho(mono img+wx) - rho(mono img)", "AUC(clf img+wx) - AUC(clf img)", "rho(weather-normalised) - rho(raw area/GW)"; n_off_cold = int(t.loc["cold", "n_off"])
F.append(dict(id="s2_weather_conditioning", title="Ambient weather limits plume visibility; conditioning on it helps a little, normalising by it does not", one_liner=f"On/off AUC is {t.loc['cold', 'auc_raw_area_per_GW']:.2f} below 5 C but {t.loc['hot', 'auc_raw_area_per_GW']:.2f} above 25 C; adding ERA5 weather to the model gains +{b.loc[B1, 'mean']:.3f} Spearman (significant) but an explicit weather-normalised plume index gains nothing.",
  datasets=[DS["s2"], DS["cems"], DS["era5"]], mechanism="Plume condensation length scales with how far the exhaust is from saturation after mixing: cold/humid air -> long plumes, hot/dry -> plume evaporates within metres.",
  method="Same held-out predictions as s2_plume_us_onoff, split by ERA5 2 m temperature, dew-point depression and season; paired plant-bootstrap (1000x) of model contrasts.",
  results=[R("AUC raw area, T<5C", t.loc["cold", "auc_raw_area_per_GW"], t.loc["cold", "n"], f"{n_off_cold} off"), R("AUC raw area, 5-15C", t.loc["cool", "auc_raw_area_per_GW"], t.loc["cool", "n"]), R("AUC raw area, 15-25C", t.loc["mild", "auc_raw_area_per_GW"], t.loc["mild", "n"]), R("AUC raw area, >25C", t.loc["hot", "auc_raw_area_per_GW"], t.loc["hot", "n"]),
           R("AUC image+weather model, >25C", t.loc["hot", "auc_mono_gbt_img+wx"], t.loc["hot", "n"], "model recovers part of the hot-weather loss"),
           R("Spearman gain from weather features (mono GBT)", b.loc[B1, "mean"], 41, f"95% CI {b.loc[B1, 'lo95']:.3f}..{b.loc[B1, 'hi95']:.3f}"),
           R("AUC gain from weather features (classifier)", b.loc[B2, "mean"], 41, f"95% CI {b.loc[B2, 'lo95']:.3f}..{b.loc[B2, 'hi95']:.3f}"),
           R("Spearman gain of weather-normalised area over raw area", b.loc[B3, "mean"], 41, f"95% CI {b.loc[B3, 'lo95']:.3f}..{b.loc[B3, 'hi95']:.3f} -> null")],
  controls="Weather-only model has almost no skill, so the gain is not load seasonality leaking through weather.", verdict="partial", known_or_novel="known physics; the quantified split by temperature on held-out plants is a modest addition",
  prior_art=["https://www.mdpi.com/2072-4292/16/7/1290"], figures=["figs/s2_summary.png"], scripts=["s2_model2.py"], caveats="The hypothesis 'a weather-conditioned model should clearly beat raw area' is only weakly supported: the gain is real but small; weather mainly tells you WHEN the method can be trusted."))
tw = aup[aup.group.isin(["natural_draft", "mixed"])]; ctl = aup[~aup.group.isin(["natural_draft", "mixed"])]
F.append(dict(id="s2_zero_shot_australia", title="US-trained plume model applied zero-shot to Australian coal plants, verified against AEMO 5-minute SCADA", one_liner=f"Rank transfers (Spearman {tw['rho_mono_gbt_img+wx'].median():.2f} median, {int((tw['rho_mono_gbt_img+wx'] > 0.4).sum())}/7 tower plants >0.4; air-cooled controls ~0) but level does not (capacity factor biased {tw['bias_cf(mono)'].median():+.2f}) and tercile accuracy is no better than baseline.",
  datasets=[DS["s2"], DS["aemo"], DS["osm"], DS["era5"], DS["cems"]], mechanism="Same plume physics; Australia never seen in training; different climate, tower designs, no wet FGD.",
  method="7 Australian plants with wet cooling towers + 3 controls (2 air-cooled, 1 once-through lake-cooled); model trained on all 41 US plants; label = mean plant MW over the 25 min before each Sentinel-2 overpass / 99.5th pct. No Australian data touched the model or any threshold.",
  results=[R("pooled Spearman(model, CF), tower plants", *g(m2, AUT, "mono_gbt_img+wx", "spearman_cf"), f"raw area {g(m2, AUT, 'raw_area_per_GW', 'spearman_cf')[0]:.3f}; before border rule 0.41")] +
          [R(f"Spearman {r.plant} ({r.group})", r["rho_mono_gbt_img+wx"], r.n, f"MAE CF {r['mae_cf(mono)']:.2f}, bias {r['bias_cf(mono)']:+.2f}") for _, r in aup.iterrows()] +
          [R(f"lowest-vs-highest load quartile AUC, {r.plant}", r.auc_low_vs_high, r.n_lo + r.n_hi) for _, r in lohi.iterrows()] +
          [R("tercile accuracy (US-defined terciles)", *g(m2, AUT, "mono_gbt_img+wx", "tercile_acc"), f"majority baseline {g(m2, AUT, 'mono_gbt_img+wx', 'tercile_majority_baseline')[0]:.3f} -> no skill")],
  controls=f"No-tower controls: Kogan Creek {ctl.set_index('plant').loc['Kogan Creek', 'rho_mono_gbt_img+wx']:+.2f}, Millmerran {ctl.set_index('plant').loc['Millmerran', 'rho_mono_gbt_img+wx']:+.2f} (as expected ~0); Eraring {ctl.set_index('plant').loc['Eraring', 'rho_mono_gbt_img+wx']:+.2f} -- a spurious NEGATIVE correlation at a plant with no plume mechanism (sun-angle/rooftop-solar duck-curve confound), which sets the single-plant noise floor at |rho|~0.3.",
  verdict="partial", known_or_novel="Climate TRACE validated on Australia with Australian training data; a strict zero-shot US->Australia test with public data is, as far as we found, not published",
  prior_art=["https://www.mdpi.com/2072-4292/16/7/1290"], figures=["figs/montage_loyyang_au.png", "figs/montage_mtpiper_au.png", "figs/s2_summary.png"], scripts=["aemo_fetch.py", "s2_model2.py", "s2_montage.py"],
  caveats="Whole-plant OFF essentially never happens in the Australian sample (1 scene), so on/off AUC abroad is untestable; Tarong and Stanwell fail (rho<0.3); only ~500 usable tower-plant scenes; first label-free source finder locked onto ash dams and mines and had to be replaced by OSM tower coordinates."))
json.dump(F, open(D+"findings_part1.json", "w"), indent=1); print(len(F), "findings (part 1)")
